mikavilpas/yazi.nvim

- lua/yazi/config.lua
Just select multiple files and hit c-v, c-s or c-t
> feat: can open multiple files in splits or tabs

- dev-documentation/lsp-renaming.md
Related: https://github.com/sxyazi/yazi/discussions/755
> docs: document how lsp file renaming works

- lua/yazi/config.lua
- lua/yazi/types.lua
- lua/yazi/window.lua
Closes #49, although I think the mouse support can be improved. I might open a new issue about this, but let's get some feedback first.
> Hack mouse support for yazi

- lua/yazi/utils.lua
- tests/yazi/open_multiple_files_spec.lua
- tests/yazi/yazi_spec.lua
Fixes https://github.com/mikavilpas/yazi.nvim/issues/60
> Fix not being able to open complex file names

- lua/yazi.lua
Might fix https://github.com/mikavilpas/yazi.nvim/issues/58
> fix: when opening a directory, insert mode is not activated

- README.md
It's kind of short though, but contributions to this section are welcome 😅
> docs: add section on contributing

- lua/yazi/config.lua
There's still a bit of manual work involved, and I think in the future it might be necessary to add some smarter way of overriding only some of the keymappings. Not sure what the best way to do this would be.
Partial overrides could also be added.
> feat: make it easier to completely override the default keymappings

- .github/workflows/release.yml
I want to start making releases that have a I have no idea how this should work. Let's see what happens.
> Versioning

- .github/workflows/linkspector.yml
Can help keep the documentation up to date
> ci: report broken links in markdown (md) files

- README.md
Closes https://github.com/mikavilpas/yazi.nvim/issues/112
> docs: add note about image previews for neovim

- .github/workflows/release-luarocks.yml
I think release-please did not trigger this for some reason.
> ci: try to fix luarocks publishing

- CHANGELOG.md
This reverts commit ba0f8830407548e958e9ccc3033fdf6d1b34f216.
> Revert "chore: remove CHANGELOG.md, trying to fix release-please (#170)"

- .github/workflows/release.yml
- release-please-config.json
The electric boogaloo
https://github.com/folke/lazy.nvim/pull/1534
> ci: try to fix release-please version updating (part 2)

- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- integration-tests/package.json
- package-lock.json
The tests were reporting false positives
> refactor(tests): make sure yazi is closed after opening a file

- integration-tests/client/testEnvironmentTypes.ts
- integration-tests/cypress.config.ts
- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/opening-directories.cy.ts
- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/hover-highlights.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/mouse.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-directories.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/toggling.cy.ts
- lua/yazi/window.lua
This broke when I added the fix from yesterday,
https://github.com/mikavilpas/yazi.nvim/commit/c9ebbf6749980680a533125ac08a0d57257c04a9
> fix: not being able to open directories with enter

- lua/yazi.lua
- lua/yazi/hijack_netrw.lua
Fixes https://github.com/mikavilpas/yazi.nvim/issues/308
> fix: `open_yazi_in_directory` error in nvim 0.10.1 & nightly

- README.md
- lazy.lua
Closes https://github.com/mikavilpas/yazi.nvim/issues/306
> docs: mention extra dependencies in README

- documentation/plugin-management.md
- lua/yazi/plugin.lua
For a real life example, see
https://github.com/mikavilpas/dotfiles/commit/abbf921f5c85087da7e272f7f1dce5f26ab97c91
> docs: add example of installing a flavor from a subdirectory

- lazy.lua
- lua/yazi/buffer_highlighting/colors.lua
- lua/yazi/buffer_highlighting/disposable_highlight.lua
- spec/yazi/colors_spec.lua
- yazi.nvim-scm-1.rockspec
I found that `yazi.nvim` only uses one file from `bufferline.nvim`, so I added that file here to make the package self-contained. Could you please merge this PR if it looks good? Thanks!
> Remove bufferline dependency

- integration-tests/package.json
- package-lock.json
In interactive mode, a change to the test file would trigger a restart of the entire test server. This is not ideal as it takes a long time to restart the server. This change will only restart the server when changes to the server files are saved.
> fix(tests): changing the tests had delay in restarting the test

- README.md
- lua/yazi/config.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/types.lua
- spec/yazi/keybinding_helpers_spec.lua
use `cwd` field created in #471 to implement feature discussed in #466.
> feat: add keymap for changing cwd to current directory

- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/utils/yazi-utils.ts
- integration-tests/package.json
- lua/yazi/renameable_buffer.lua
- lua/yazi/utils.lua
- pnpm-lock.yaml
Fixes https://github.com/mikavilpas/yazi.nvim/issues/556
> fix: avoid "E13: File exists" error after renaming a file

- lua/yazi/utils.lua
- package.json
> Fix renaming error

- .github/workflows/test.yml
https://github.com/cypress-io/github-action/issues/1246
> ci: fix cypress caching issue with pnpm

- lua/yazi/keybinding_helpers.lua
- lua/yazi/log.lua
- package.json
I saw this here and think it's a good idea
- https://github.com/Saghen/blink.cmp/pull/722
Implementations I found for these:
https://github.com/folke/snacks.nvim/blob/98df370703b3c47a297988f3e55ce99628639590/lua/snacks/notify.lua#L23
https://github.com/rcarriga/nvim-notify/blob/fbef5d32be8466dd76544a257d3f3dce20082a07/doc/nvim-notify.txt#L48
> feat: add title to notify messages

- README.md
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/cd-to-buffer-with-ya-emit.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/cd-to-buffer-without-ya-emit-reveal.cy.ts
- integration-tests/cypress/support/tui-sandbox.ts
- integration-tests/package.json
- integration-tests/test-environment/.config/nvim/init.lua
- integration-tests/test-environment/config-modifications/modify_yazi_config_don't_use_ya_emit_reveal.lua
- lua/yazi/health.lua
- pnpm-lock.yaml
- spec/yazi/health_spec.lua
- spec/yazi/yazi_spec.lua
Now that yazi version 0.4.0 is older than a month, we're adapting to
some minor breaking changes.
https://github.com/sxyazi/yazi/releases/tag/v0.4.0
> feat!: require yazi 0.4.0 or later from 2024-12-08

- README.md
just noticed the update, thanks for the handy extension!
> chore: update required yazi version in README

- README.md
Thanks @ZcyhFromC for the tip!
> Organize the docs a bit and add a Powershell specific tip

- README.md
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/integrations.cy.ts
- integration-tests/test-environment/config-modifications/modify_yazi_config_use_snacks_picker.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/types.lua
This also drive-by fixes #703, which I can put in a separate PR if that'd be preferred.
> feat: add integration with snacks picker

- .github/workflows/typecheck.yml
https://github.com/stevearc/nvim-typecheck-action/pull/3
> ci: disable typecheck action for now

- .github/workflows/typecheck.yml
https://github.com/stevearc/nvim-typecheck-action/pull/3
> ci: reenable the typecheck action

- lua/yazi/health.lua
Related to https://github.com/mikavilpas/yazi.nvim/issues/780
> fix(health): add warning if snacks library is not found

- lua/yazi/health.lua
Closes https://github.com/mikavilpas/yazi.nvim/issues/792
> fix(health): checkhealth fails if `config.keymaps = false`

- README.md
Closes https://github.com/mikavilpas/yazi.nvim/issues/802
More information can be found in the issue.
> docs: add cleaner way of disabling netrw

- README.md
- lua/yazi/process/yazi_process.lua
Closes https://github.com/mikavilpas/yazi.nvim/issues/855
> docs: mention dependencies earlier in the README

- .github/workflows/test.yml
- package.json
> ci: bump yazi version to nightly

- .github/workflows/test.yml
- integration-tests/package.json
- package.json
- pnpm-lock.yaml
Bumps the npm-dependencies group with 4 updates in the / directory: [@eslint/js](https://github.com/eslint/eslint/tree/HEAD/packages/js), [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node), [eslint](https://github.com/eslint/eslint) and [type-fest](https://github.com/sindresorhus/type-fest).
Bumps the npm-dependencies group with 4 updates in the /integration-tests directory: [@eslint/js](https://github.com/eslint/eslint/tree/HEAD/packages/js), [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node), [eslint](https://github.com/eslint/eslint) and [type-fest](https://github.com/sindresorhus/type-fest).
Updates `@eslint/js` from 9.23.0 to 9.24.0
- [Release notes](https://github.com/eslint/eslint/releases)
- …
> Update ci yazi version

- lua/yazi/process/ya_process.lua
- package.json
> refactor: require event_handling modules only once

- integration-tests/cypress/e2e/yazi-keymappings.cy.ts
- lua/yazi/keybinding_helpers.lua
Closes https://github.com/mikavilpas/yazi.nvim/issues/914
> fix: do not crash cycle buffers if only one is visible

- documentation/plugin-management.md
Closes https://github.com/mikavilpas/yazi.nvim/issues/936
> docs(plugin): add an example of multiple monorepo plugins

- .github/workflows/linkspector.yml
- reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: unexpected EOF
- https://github.com/UmbrellaDocs/action-linkspector/issues/30
> ci: reenable linkspector action

- .github/workflows/test.yml
https://github.com/sxyazi/yazi/commit/aae3f9ea4ad280a0e7b5596e137f38ec6f6f698b
> ci: bump e2e test yazi version v25.5.31 -> bleeding edge

- README.md
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/opening-files.cy.ts
- integration-tests/package.json
- integration-tests/test-environment/config-modifications/make_yazi_fullscreen.lua
- lua/yazi/types.lua
- lua/yazi/window.lua
- pnpm-lock.yaml
Example configuration:
```lua
---@module "yazi"
require("yazi").setup(
---@type YaziConfig
{
floating_window_scaling_factor = 1,
yazi_floating_window_zindex = 200,
}
)
```
https://github.com/mikavilpas/yazi.nvim/blob/69a628e48612fc54de8a9166e14a47e13e24495e/integration-tests/test-environment/config-modifications/make_yazi_fullscreen.lua?plain=1#L1-L9
Closes https://github.com/mikavilpas/yazi.nvim/issues/1014
> feat: can set the zindex of the yazi floating window

- .github/workflows/linkspector.yml
- documentation/yazi-keymappings.md
- integration-tests/cypress/e2e/reading-events.cy.ts
- integration-tests/package.json
- integration-tests/test-environment/.config/yazi/keymap.toml
- integration-tests/test-environment/config-modifications/notify_custom_events.lua
- package.json
- pnpm-lock.yaml
Related discussion:
https://github.com/mikavilpas/yazi.nvim/discussions/1022
> docs: document how to send the selected file in a custom event

- lua/yazi/renameable_buffer.lua
Preparation for possibly dropping plenary.nvim
https://github.com/mikavilpas/yazi.nvim/issues/1050
> refactor: remove plenary.iterators usage

- .github/workflows/test.yml
- integration-tests/cypress/e2e/integrations.cy.ts
- integration-tests/package.json
- pnpm-lock.yaml
> Dependency updates

- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/opening-files.cy.ts
- integration-tests/cypress/support/tui-sandbox.ts
- integration-tests/package.json
- pnpm-lock.yaml
https://github.com/mikavilpas/tui-sandbox/pull/533
Includes https://github.com/mikavilpas/tui-sandbox/pull/533
> test: use tui-sandbox `nvim.doFile()` to load Lua files

- integration-tests/test-environment/.config/nvim_integrations/prepare.lua
https://github.com/EmmyLuaLs/emmylua-analyzer-rust/releases/tag/0.12.0
> test: bump emmylua_ls from 0.11.0 to 0.12.0

- .github/workflows/test.yml
> ci: use apt-get install only once

- lua/yazi/window.lua
Closes https://github.com/mikavilpas/yazi.nvim/issues/1150
> fix: fix yazi shifting to the left when opening for the first time

- .github/workflows/test.yml
https://github.com/sxyazi/yazi/commit/eb537733a2c5b09649b56284b74dbdd4e70006ec
> ci: bump yazi nightly from 2025-08-23 to 2025-08-30
