- lua/yazi.lua
- lua/yazi/renameable_buffer.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- tests/yazi/example_spec.lua
- tests/yazi/rename_spec.lua
- tests/yazi/renameable_buffer_spec.lua
In the previous implementation, renaming a file multiple times in yazi did not sync properly to nvim.
This is now fixed.
> Fix successive renames not being handled

- lua/yazi.lua
- tests/yazi/yazi_spec.lua
This is a breaking change because it changes the signature of the `yazi()` function.
It should be easy to migrate to the new signature though!
> feat!: allow customizing the config when calling yazi()

- lua/yazi.lua
- lua/yazi/renaming.lua
- tests/yazi/rename_spec.lua
This is preparation for the next step, which is to process many types of items from yazi, not just rename events.
> refactor(renaming): rename one file at a time, not all at once

- README.md
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/types.lua
- tests/yazi/open_multiple_files_spec.lua
- tests/yazi/yazi_spec.lua
In yazi, it's possible to open one file or multiple files. Now, if a single file is opened, there is no change in behavior. However, if multiple files are opened, the quickfix list will show all the files that are opened.
> feat: show multiple selected files in the quickfix list

- lua/yazi/event_handling.lua
- tests/yazi/delete_spec.lua
- tests/yazi/trash_spec.lua
sometimes I find myself renaming a file to a new name, and then
renaming it back to the original name. This causes the file to be
closed and then opened again, which is not necessary. This commit
fixes this issue by checking if the file is already open before
closing it.
> fix: don't close a removed file if renamed to later

- lua/yazi.lua
- lua/yazi/event_handling.lua
- lua/yazi/utils.lua
- tests/yazi/rename_spec.lua
This could happen in the following case:
- open files A and B
- open yazi
- rename A to B
- quit yazi
It would cause a crash when processing events, causing an error to be printed to the user, and stopping the processing of events.
> fix: crash when renaming to an open buffer

- lua/yazi/event_handling.lua
- lua/yazi/lsp/delete.lua
- lua/yazi/lsp/lsp_util.lua
- lua/yazi/lsp/rename.lua
- lua/yazi/utils.lua
- tests/yazi/lsp_delete_spec.lua
- tests/yazi/lsp_rename_spec.lua
feat(lsp): apply changes to related files when a file is renamed
Previously the language server could easily get out of sync when a file
was renamed in yazi. The language server would e.g. have import
statements that referenced the old file name.
This feature only applies when a language server is running and the
server has support for renaming. What now happens is:
- neovim is open and a language server is running
- neovim opens yazi
- yazi renames (or moves) a file that's part of the current workspace
- yazi is closed
- neovim sends a request to the language server to rename the file
- the language server responds with a list of changes to other files
- neovim applies those changes to the other files but doesn't save
changes automatically (at least not for me)
I tested this in a …
> Request lsp help when renaming and deleting files

- lua/yazi/event_handling.lua
- lua/yazi/utils.lua
This fixes an error in the following case:
- in a directory containing many files, have only one file open in neovim (with other files in the directory not open)
- open yazi
- rename the directory containing the files
At this point, the LSP server would receive a notification of the rename only for the file that was open in neovim, and not for the other files in the directory. This would cause the LSP server to only apply changes related to the one open file.
> fix(lsp): only notifying lsp of renames for open buffers

- lua/yazi.lua
- lua/yazi/health.lua
Fixes https://github.com/mikavilpas/yazi.nvim/issues/32
Note: I could have added support for a yazi version without --local-events support, but I think it's much better to point the user to upgrade their yazi version instead so that they also get other fixes and features with the new yazi version.
> feat: warn when the yazi version is too old

- lua/yazi/lsp/lsp_util.lua
- lua/yazi/lsp/rename.lua
In projects where there are many types of files, such as readme files (markdown) and code files (let's say, typescript), there was an inconvenience that the currently active lsp servers would not be notified unless they were connected to the current buffer.
That means that if you were editing a markdown file and wanted to rename a typescript file using yazi, the lsp server for typescript would not be notified of the rename.
> fix(lsp): renaming only notified the lsp for the current file

- .github/workflows/test.yml
- README.md
- lua/yazi/health.lua
The check is not enforced, so using 0.2.4 should still work. However, the latest version of yazi is supported right now.
> feat!: require yazi version 0.2.5 (previously required 0.2.4)

- README.md
The curly braces surrounding `desc` in the instructions to install using `lazy.nvim` should be removed.
> Remove curly braces in lazy.nvim instructions

- lua/yazi/window.lua
...from a yazi session. It seemed to close the window twice, which caused some issues (not sure why).
Looks like this was accidentally broken when I added experimental support for scrolling in
https://github.com/mikavilpas/yazi.nvim/issues/49
Should be fixed now.
> fix: not being able to open yazi for directories

- lua/yazi.lua
- lua/yazi/window.lua
When the neovim window is resized, the yazi floating window will now resize itself.
Note that this doesn't currently work in some cases apparently because of a bug in neovim. You can subscribe to
https://github.com/mikavilpas/yazi.nvim/issues/39 for updates.
> feat: basic support for resizing the yazi window

- lua/yazi.lua
- lua/yazi/openers.lua
- lua/yazi/utils.lua
- tests/yazi/open_multiple_files_spec.lua
- tests/yazi/yazi_spec.lua
This also fixes an issue where the currently open file would not get preselected when yazi was opened when the file had complex characters such as '$' in it.
related to #60 #61
> fix: complex character file name resolution for multiple files

- README.md
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/types.lua
- tests/yazi/open_dir_spec.lua
- tests/yazi/yazi_spec.lua
This mainly helps with developing the plugin by preventing conflicts of multiple parallel yazi.nvim instances.
The file paths can still be configured but I removed them from the readme because most users don't have to.
> refactor: use unique temp files

- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/health.lua
- lua/yazi/log.lua
- lua/yazi/types.lua
- lua/yazi/utils/path.lua
- tests/yazi/open_dir_spec.lua
- tests/yazi/yazi_spec.lua
Related to #67 but this might not be a perfect solution right away
feat(log): add possibility for debug logging to diagnose issues
The log can be enabled by specifying it in the yazi.nvim config:
```lua
-- ... other config options here
---@type YaziConfig
opts = {
log_level = vim.log.levels.DEBUG,
},
```
Only DEBUG level is supported for now.
You can find out the location of the log file by running the following command:
```vim
:checkhealth yazi
```
> Try to fix windows path issue

- lua/yazi.lua
- lua/yazi/health.lua
- lua/yazi/utils/path.lua
- tests/yazi/open_dir_spec.lua
- tests/yazi/yazi_spec.lua
Continuing the work started in #73. Got stalled because of build system issues 🤷🏻‍♂️
> Windows fixes

- lua/yazi.lua
- lua/yazi/event_handling.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- tests/yazi/open_dir_spec.lua
- tests/yazi/yazi_spec.lua
This PR adds support for custom hook implementations to know what the last directory was when yazi was closed. It can be used to e.g. change the current working directory in neovim.
In the future, I am thinking I can add some mappings that also use this, for example to do a grep (file content search) operation on the selected directory only. More ideas are also welcome 👍🏻 
related: https://github.com/mikavilpas/yazi.nvim/issues/83
> feat: allow yazi_closed_successfully hook to know the last yazi dir

- README.md
- lazy-lock.json
- lua/yazi/config.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- tests/yazi/yazi_spec.lua
feat: <c-s> closes yazi and starts telescope.nvim's live_grep
The live_grep is constrained to the last directory yazi was in (that is,
the current yazi directory when entering this key combination).
This can be used to comfortably explore parts of the current project (on
the directory level) in an ad hoc fashion.
The search action can be configured in the user's configuration in case
they want to use some other method of searching (even another plugin
entirely), or customize it, or disable it completely.
> feat: <c-s> closes yazi and starts telescope.nvim's live_grep

- .github/workflows/linkspector.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/style.yml
- .github/workflows/test.yml
- .github/workflows/typecheck.yml
- .github/workflows/updater.yml
* **[actions/setup-node](https://github.com/actions/setup-node)** published a new release **[v4.0.2](https://github.com/actions/setup-node/releases/tag/v4.0.2)** on 2024-02-07T04:51:19Z
* **[googleapis/release-please-action](https://github.com/googleapis/release-please-action)** published a new release **[v4.1.1](https://github.com/googleapis/release-please-action/releases/tag/v4.1.1)** on 2024-05-14T20:39:29Z
* **[leafo/gh-actions-lua](https://github.com/leafo/gh-actions-lua)** published a new release **[v10.0.0](https://github.com/leafo/gh-actions-lua/releases/tag/v10.0.0)** on 2023-01-31T18:40:04Z
* **[actions/checkout](https://github.com/actions/checkout)** published a new release **[v4.1.6](https://github.com/actions/checkout/releases/tag/v4.1.6)** on 2024-05-16T18:11:28Z
* …
> Update GitHub Action Versions

- lua/yazi/plugin.lua
- tests/yazi/plugin_spec.lua
When a plugin or flavor is first installed and later updated, the link to the plugin or flavor's directory is already in place. This caused an error when the plugin or flavor was installed again (updated). The error did not actually do anything disruptive, but it was annoying.
Now, reinstalling checks if the symlink is already in place and does nothing if it is.
> fix(plugins): fix failure on repeated installation

- lua/yazi.lua
- lua/yazi/event_handling.lua
- lua/yazi/utils.lua
- tests/yazi/delete_spec.lua
- tests/yazi/trash_spec.lua
When a buffer was opened in neovim and being edited, and then yazi
deleted it, the buffer was not closed. I'm not sure what broke it.
The fix is to close the buffer asynchronously. I don't understand why
that fixes the issue, but it does.
`vim.await` is really cool. I found it here:
https://www.reddit.com/r/neovim/comments/1cv5q45/comment/l4s2ya0/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
Buffers are processed when renaming, deleting, and trashing files in
yazi. Previously all open buffers were processed, but now only normal
buffers are.
This actually doesn't have a big impact on performance. I just wanted to
have a `perf` commit in the history 😄. Perhaps in big projects it might
be noticeable, or if some future feature will require more …
> Fix deletion not closing open deleted buffers

- Makefile
- spec/yazi/yazi_spec.lua
This might cause trouble for developers who want to run focused tests. Better to avoid it.
> ci: check that there are no #focus tags left over in the tests

- lua/yazi/window.lua
For me, the following bug was happening:
- I start yazi and see yazi in the floating terminal
- I press `<esc><esc>` (esc twice)
- pressing j does not make yazi move the focus to the next file. Instead the terminal seems to be in normal mode and the cursor moves down.
This only happens once in the neovim session.
It was possible to work around this issue by pressing `i` to seemingly enter insert mode again 😄
This commit works around the issue by always entering insert mode when the mode changes.
This seems like a pretty stupid solution, so let's hope it causes no problems 🤞🏻
> fix: exiting insert mode with "<esc><esc>"

- .gitignore
- lua/yazi.lua
Yazi.nvim has a feature where you can specify `open_for_directories = true` to automatically open yazi when opening a directory in Neovim.
In some cases, opening a directory when starting Neovim from the command line would show yazi, but the window under yazi was selected. Yazi was supposed to have been focused instead.
This was due to the default netrw file manager not having a file name for the buffer that was opened. I don't know why this only happened in some cases.
Fixes https://github.com/mikavilpas/yazi.nvim/issues/58
> fix: opening "nvim dir/" may focus wrong window

- lua/yazi.lua
- lua/yazi/openers.lua
- lua/yazi/utils.lua
I am using AstroNvim and encountered an issue that will result in one empty buffer.
background:
AstroNvim uses alpha.nvim as a greeting.
reproduce procedure:
1. use astronvim
2. add yazi.nvim with below config
``` lua
---@type LazySpec
return {
"mikavilpas/yazi.nvim",
event = "VeryLazy",
keys = {
-- 👇 in this section, choose your own keymappings!
{
"<leader>-",
function() require("yazi").yazi() end,
desc = "Open the file manager",
},
{
-- Open in the current working directory
"<leader>+",
function() require("yazi").yazi(nil, vim.fn.getcwd()) end,
desc = "Open the file manager in nvim's working directory",
},
},
---@type YaziConfig
opts = {
-- open_for_directories = true,
log_level = vim.log.levels.INFO,
},
}
```
3. open neovim , leader- to open yazi,select a file to open
4. will look like …
> fix: open file results in one empty buffer

- lua/yazi/config.lua
- lua/yazi/window.lua
This PR is for testing an idea that came up in #126
> refactor: remove hacky workaround for <esc><esc> in insert mode

- README.md
- repro.lua
> If your plugin needs setup(), then create a simple lazy.lua file like this:
>
>   return { "me/my-plugin", opts = {} }
>
> Plugins that are pure lua libraries should be lazy-loaded with lazy = true.
>
> { "nvim-lua/plenary.nvim", lazy = true }
>
> Only use dependencies if a plugin needs the dep to be installed AND loaded. Lua plugins/libraries are automatically loaded when they are require()d, so they don't need to be in dependencies.
https://lazy.folke.io/developers#best-practices
> docs: adapt to new lazy.nvim best practices for dependencies

- README.md
- integration-tests/package.json
- integration-tests/test-environment/test-setup.lua
- lazy.lua
As of lazy.nvim 11, packages can now specify their own dependencies and configuration. This means that users of lazy.nvim no longer need to specify plenary.nvim as a dependency. If any dependencies are added in the future, they will be automatically installed by lazy.nvim.
This is a backwards-compatible change.
<https://lazy.folke.io/news#11x>
> feat: lazy.nvim users no longer need to specify dependencies

- documentation/reproducing-issues.md
This plugin includes a `repro.lua` file that can be used to start neovim with a minimal, known configuration. This is useful for reproducing issues.
If the reproduction script had been run some time ago, the dependencies might be out of date. This commit updates the script to update the dependencies before starting neovim.
> fix(repro): update the repro script to update the dependencies

- lua/yazi/log.lua
This bug caused useless log lines to be written to the log file. If you
want to delete your log file, you can find it with `:checkhealth yazi`
> fix: not being able to disable writing DEBUG logs

- lua/yazi/log.lua
I left this in accidentally, and it logged a confusing message every time.
some discussion can be found in
https://github.com/mikavilpas/yazi.nvim/commit/8f251defe31ce7b3e623b499e08a7c558d79bfdb
> fix: remove extra debug logging

- .github/workflows/release.yml
This adds the release-please token to the release workflow to fix an issue that occurred in https://github.com/mikavilpas/yazi.nvim/pull/154
Looks like release-please is able to create a release PR, but not able to start workflows using the default `GITHUB_TOKEN`.
- https://github.com/googleapis/release-please-action/issues/818
- https://github.com/marketplace/actions/release-please-action
- https://github.com/peter-evans/create-pull-request/issues/48
> ci: add release-please token to fix stalled releases

- integration-tests/package.json
- integration-tests/test-environment/test-setup.lua
- package.json
Fixes the following issues:
- an extra `cypress open` was launched when running tests in ci. They should have been run headlessly.
- swapfiles were occasionally created in the test environment, which could cause tests to fail. This only happened developing locally.
> ci: make integration-tests more robust

- README.md
- documentation/plugin-manager.md
- lua/yazi/plugin.lua
- spec/yazi/plugin_spec.lua
Some plugins are not found at the root of the repository, but in a
subdirectory. This change allows specifying a subdirectory when
installing a plugin.
It corresponds to using `#` in the plugin URL when installing plugins
without yazi.nvim with the `ya pack` command.
```sh
ya pack -a redbeardymcgee/yazi-plugins#keyjump
```
Is the same as:
```lua
---@type LazySpec
{
"redbeardymcgee/yazi-plugins",
lazy = true,
build = function(plugin)
require("yazi.plugin").build_plugin(plugin, { sub_dir = "keyjump.yazi" })
end,
},
```
> Allow installing yazi plugins from a plugin monorepo

- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- lua/yazi/event_handling.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- spec/yazi/health_spec.lua
fix: not handling bulk renaming events correctly
This commit fixes a bug where yazi.nvim would not handle bulk renaming
events like rename,move,delete events are handled. This bug had the
following impact:
- open buffers would not be renamed after a bulk rename operation
- LSP servers would not be notified of the rename operation
> Support yazi bulk renaming events

- README.md
- integration-tests/client/testEnvironmentTypes.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/hover-highlights.cy.ts
- integration-tests/package.json
- integration-tests/server/server.ts
- integration-tests/test-environment/config-modifications/modify_yazi_config_and_add_hovered_buffer_background.lua
- integration-tests/test-environment/config-modifications/use_light_neovim_colorscheme.lua
- lazy.lua
- lua/yazi/buffer_highlighting/disposable_highlight.lua
- lua/yazi/buffer_highlighting/highlight_hovered_buffer.lua
- lua/yazi/config.lua
- lua/yazi/health.lua
- lua/yazi/types.lua
- package-lock.json
- yazi.nvim-scm-1.rockspec
(Hover highlighting is a feature currently requiring opt-in that was added in #180)
This works with the latest yazi when `use_ya_for_events_reading = true` is specified. To learn more about enabling this, see <https://github.com/mikavilpas/yazi.nvim/pull/152>
This will be the default behaviour when yazi 0.3 is released.
> Dark mode
>
> (neovim: catppuccin macchiato, yazi: catppuccin macchiato)
https://github.com/user-attachments/assets/f4c94fc0-8e8a-41b5-94ee-4ecef201b6e2
> Light mode
>
> (neovim: catppuccin latte, yazi: catppuccin macchiato)
>
> Just focus on the background color of the hovered buffer as I couldn't be bothered to change my yazi theme 😅
https://github.com/user-attachments/assets/6f634d67-3a64-4b53-a097-46b49849b40e
This change adds default colors for the hover …
> feat!: add default colors for hover highlighting

- README.md
I think this is happening because I changed the name of the default branch `master` -> `main`. Lazy.nvim seems to complain by default if the branch disappears.
This seems to be the same issue, and provides a workaround for it:
https://github.com/folke/lazy.nvim/issues/1052#issuecomment-1738770214
So: uninstalling and reinstalling resolves the issue. I added a notice about this to the README.md file.
> docs: add notice about branch name change causing issues

- lua/yazi/plugin.lua
- spec/yazi/plugin_spec.lua
This happened to me when this plugin was moved to a different hosting provider:
- https://github.com/DreamMaoMao/keyjump.yazi
- https://gitee.com/DreamMaoMao/keyjump.yazi
After I changed my lazy.nvim spec to this, I got an error because the symlink already existed:
```lua
{
name = "keyjump.yazi",
url = "https://gitee.com/DreamMaoMao/keyjump.yazi.git",
lazy = true,
build = function(plugin)
require("yazi.plugin").build_plugin(plugin)
end,
},
```
This change makes it so that the symlink is removed before creating a new one. Realistically, this is what the user wants most of the time anyway.
> feat(plugin): overwrite existing symlinks when installing plugins

- README.md
- documentation/installing-yazi-from-source.md
This came up as a need in https://github.com/mikavilpas/yazi.nvim/issues/210
> docs: add instructions for installing yazi from source

- lua/yazi/renameable_buffer.lua
- spec/yazi/renameable_buffer_spec.lua
I experienced this issue when hovering over my yazi.nvim lazy.nvim spec. It's symlinked to the actual file in the lazy.nvim repository.
These are the same file:
```sh
/Users/mikavilpas/dotfiles/.config/nvim/lua/plugins/my-file-manager.lua
/Users/mikavilpas/.config/nvim/lua/plugins/my-file-manager.lua
```
This commit fixes the issue by resolving the real path of the file before
comparing it to the path of the buffer.
Closes https://github.com/mikavilpas/yazi.nvim/issues/195
> fix: symlinked files cannot be highlighted when hovered

- .github/workflows/test.yml
- README.md
- integration-tests/test-environment/config-modifications/modify_yazi_config_to_use_ya_as_event_reader.lua
- lua/yazi/config.lua
- lua/yazi/health.lua
- lua/yazi/process/legacy_events_from_file.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/types.lua
- lua/yazi/yazi_process.lua
- spec/yazi/health_spec.lua
This is a technical change with no change in features for the end user. Right now you can opt in to trying it out by setting `use_yazi_client_id_flag = true` in your config (run `:checkhealth yazi` afterwards).
This will probably be the default mode of communication in the future.
Before this change, real time communication with the embedded yazi instance has been possible, but it has had some limitations:
- yazi.nvim had the possibility of sending commands to yazi, but the communication has been global, meaning that all yazi instances running on the system have been able to receive these messages. This has been too dangerous to implement, as making yazi do any actions could have unintended side effects if multiple yazis execute the same actions, potentially in different directories on …
> feat: add targeted communication with the yazi instance (opt-in)

- lua/yazi/process/ya_process.lua
There was a bug in opting in to the feature from 8114817 (feat: add targeted communication with the yazi instance (opt-in) (#225)). Even if you had not set `use_yazi_client_id_flag = true` in your config, the newest yazi was still required.
This commit fixes that bug by removing the passing of the `yazi_id` (roll forward style). Later changes can still utilize the feature and build on top of this.
> fix: crash without newest yazi

- lua/yazi/process/legacy_events_from_file.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/yazi_process.lua
This reverts commit de4e79e07867c29c871a91d464c421ca1f26ba33.
> refactor: reenable the opt-in `--client-id` flag for yazi

- README.md
- integration-tests/client/testEnvironmentTypes.ts
- integration-tests/cypress.config.ts
- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/reading-events.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/cd-to-buffer.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/hover-highlights.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/hover-utils.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- integration-tests/server/server.ts
- integration-tests/test-environment/other-subdirectory/other-sub-file.txt
- integration-tests/test-environment/routes/posts.$postId/adjacent-file.txt
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/process/yazi_process_api.lua
- lua/yazi/types.lua
- spec/yazi/helpers/fake_yazi_process.lua
- spec/yazi/yazi_spec.lua
This feature is only supported for the latest yazi version. For now,
you have to compile yazi from source to be able to use it. See the
readme for instructions on how to do this.
https://github.com/user-attachments/assets/972542d2-d2ab-4d65-99a9-cad39b43ceeb
If you have files open in split windows in Neovim, and have started yazi, you can now press the `tab` key to make yazi jump to the directory of the next open buffer. This is useful when you have multiple files open in different directories and want to quickly jump between them.
Right now this has the following limitation: it can only jump to the directory of the next open buffer, but not necessarily focus the buffer in yazi. This is because yazi doesn't have a built-in way to jump to a specific file, only a directory. This is …
> feat: pressing `tab` in yazi jumps to dir of next open split

- lua/yazi/keybinding_helpers.lua
These errors are minor and only occurred in edge cases. They reported error messages that were meant for developers, and the fix is not to report these messages and simply abort.
> Fix buffer cycling small errors

- README.md
- documentation/plugin-management.md
To be clear, yazi.nvim does almost nothing, with lazy.nvim doing all the heavy lifting.
Also I now consider the plugin management system stable, as it has been working with no issues for a few months now in my own use.
> docs: rename plugin-manager.md to plugin-management.md

- README.md
- integration-tests/test-environment/test-setup.lua
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/types.lua
- lua/yazi/window.lua
- spec/yazi/yazi_spec.lua
This adds a new configuration option `keymaps` that can be used to customize the keybindings that are active when yazi is open and focused. You might want to do this if you have a _yazi_ keymap that conflicts with a yazi.nvim keymap, or if you just prefer different keybindings.
If you have your lua LSP server setup, you can now get nice autocompletion for all of the available keymaps.
The current defaults have not changed, and are as follows:
```lua
keymaps = {
open_file_in_vertical_split = '<c-v>',
open_file_in_horizontal_split = '<c-x>',
open_file_in_tab = '<c-t>',
grep_in_directory = '<c-s>',
cycle_open_buffers = '<tab>',
},
```
BREAKING CHANGE: If you, for some reason, relied on the fact that `set_keymappings_function` removed all the built-in keymappings, you will need to change your …
> feat!: allow customizing keymaps more clearly

- README.md
- integration-tests/client/testEnvironmentTypes.ts
- integration-tests/cypress.config.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/hover-highlights.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/integrations.cy.ts
- integration-tests/cypress/support/commands.ts
- integration-tests/test-environment/test-setup.lua
- lua/yazi/config.lua
- lua/yazi/types.lua
- package-lock.json
This commit adds an integration with grug-far.nvim, a plugin that provides a way to search and replace in the current working directory. It was recently added in LazyVim as the default, and it's really easy to use.
When you press the keybinding (default: `<c-g>`), yazi will close and grug-far.nvim will open with the current directory prefilled in the search field. This makes it easy to search and replace in that directory only. Note that this only seems to work when the target directory is under cwd, so it's not possible to search in a parent directory.
https://github.com/user-attachments/assets/50e4b5d0-3795-482c-b107-0f5237a8ed1e
The integration is added as a keymap in the config. The keymap is set to `<c-g>` by default, but it can be changed in the config.
To configure it, set one of …
> feat: add optional search and replace integration (grug-far.nvim)

- integration-tests/client/testEnvironmentTypes.ts
- integration-tests/cypress/e2e/lazy-loading.cy.ts
- integration-tests/server/server.ts
- integration-tests/test-environment/config-modifications/report_loaded_yazi_modules.lua
- lua/yazi.lua
Previously yazi.nvim would load most of its modules up front when required. This is not ideal as typically this delays Neovim's startup time. Although the delay is measured in milliseconds, it might add up if tens of other plugins need to be loaded too.
This commit changes the behavior so that yazi.nvim only loads the modules when they are actually needed. The number of loaded modules has changed from 17 to 7, but I did not measure the startup time difference.
> perf: lazy load yazi.nvim modules by default

- integration-tests/cypress/e2e/using-ya-to-read-events/integrations.cy.ts
- lua/yazi/config.lua
There was a bug in the grug-far integration (the default search and replace integration in yazi.nvim) where it was not able to search outside of the current working directory. This was due to the fact that the file path to search in was passed in `Files Filter` instead of in `Flags`, which is the correct place to pass the file path.
https://github.com/MagicDuck/grug-far.nvim/issues/146
> fix: grug-far integration not being able to search outside of the cwd

- README.md
- documentation/plugin-management.md
- spec/yazi/plugin_spec.lua
Looks like keyjump has been deprecated and easyjump is the new name for it.
> docs: update keyjump plugin to easyjump plugin

- integration-tests/cypress/e2e/lazy-loading.cy.ts
- lazy.lua
- lua/yazi.lua
- lua/yazi/log.lua
- lua/yazi/lsp/delete.lua
- lua/yazi/lsp/embedded/lsp-file-operations.lua
- lua/yazi/lsp/embedded/lsp-file-operations/did-create.lua
- lua/yazi/lsp/embedded/lsp-file-operations/did-delete.lua
- lua/yazi/lsp/embedded/lsp-file-operations/did-rename.lua
- lua/yazi/lsp/embedded/lsp-file-operations/log.lua
- lua/yazi/lsp/embedded/lsp-file-operations/utils.lua
- lua/yazi/lsp/embedded/lsp-file-operations/will-create.lua
- lua/yazi/lsp/embedded/lsp-file-operations/will-delete.lua
- lua/yazi/lsp/embedded/lsp-file-operations/will-rename.lua
- lua/yazi/lsp/rename.lua
There were some edge cases that caused issues when renaming files with LSP servers. Hopefully fix all of them by using the implementation that's also shared by neotree and nvim-tree:
https://github.com/antosha417/nvim-lsp-file-operations
Thanks @chaozwn for suggesting the fix!
Closes <https://github.com/mikavilpas/yazi.nvim/issues/80>
This work was started in
https://github.com/mikavilpas/yazi.nvim/pull/190 where the idea is to add a dependency on nvim-lsp-file-operations, but that PR has become slightly stalled for now.
This PR is a temporary fix to this stalling by simply embedding the new package inside yazi.nvim for now. When the issues in the PR have been resolved, the embedding can be removed.
> fix: LSP renaming did not work in some cases

- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- lua/yazi/utils.lua
When a file was renamed once, the buffer name was updated correctly. But when the file was renamed a second time, the buffer name was not updated.
Anyway, this is quite a rare bug, so I don't expect a huge impact one way or the other.
> fix: renaming a file twice not updating the buffer name

- lua/yazi/config.lua
See this for more information:
https://github.com/MagicDuck/grug-far.nvim/issues/154
> fix: grug-far appending extra text at the end of replaced files

- lua/yazi/config.lua
- spec/yazi/grug_far_spec.lua
This change allows the grug-far integration to work with paths that contain spaces. It escapes spaces in the path before passing it to grug-far.
This was suggested by @MagicDuck in
https://github.com/mikavilpas/yazi.nvim/commit/be2ac43a530b9b8c8b1a6185f07fac13f128f046
👍🏻👍🏻
> fix: escape spaces in paths for grug-far integration

- integration-tests/client/client.ts
- integration-tests/client/validateMouseEvent.ts
- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/mouse.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- integration-tests/cypress/support/commands.ts
- integration-tests/eslint.config.mjs
- integration-tests/server/server.ts
- lua/yazi/window.lua
The floating terminal that shows yazi running can lose focus when e.g.
clicked outside of. This commit adds an autocmd that closes the floating
terminal in these cases.
The reason for this is that it's inconvenient to navigate back to the
floating terminal to close it manually. Even if you did this, it was in
normal mode - not insert mode which is typically what you want to be in
when you're using yazi.
> fix: close the floating terminal if it loses focus

- README.md
- integration-tests/client/testEnvironmentTypes.ts
- integration-tests/cypress/e2e/help-menu.cy.ts
- integration-tests/server/server.ts
- integration-tests/test-environment/config-modifications/modify_yazi_config_and_set_help_key.lua
- lua/yazi/config.lua
- lua/yazi/types.lua
When yazi is open, you can now press `<f1>` to show a help menu with all the keybindings. This is useful for new users who are not yet familiar with the keybindings.
> feat: can toggle help menu with `<f1>` key in the yazi window

- .gitignore
- README.md
- integration-tests/client/testEnvironmentTypes.ts
- integration-tests/cypress.config.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/integrations.cy.ts
- integration-tests/test-environment/routes/posts.$postId/should-be-excluded-file.txt
- lua/yazi/config.lua
- lua/yazi/types.lua
Previously the search and replace operation would be applied to all files in the directory where the operation was started. This commit adds a feature to limit the search and replace operation to only the files that were visually selected (with `v` or `<space>` by default in yazi) in the yazi view.
> Demo: I select some files using `<space>`, and then press `<c-g>` to open the default search and replace integration (grug-far.nvim). The search is limited to the selected files only.
https://github.com/user-attachments/assets/5ce6feac-c355-443c-b9f3-b1f514eb1583
This allows fine tuning of the search and replace operation to only the files that are relevant to the user.
> feat: can limit search and replace to selected files only

- lua/yazi/health.lua
- spec/yazi/health_spec.lua
When `open_for_directories` is set to `true`, the user should be instructed to load yazi when Neovim starts. This is because the autocmds that yazi sets up to load the directories need to be set up before a directory is opened.
> feat(health): add instructions for `open_for_directories`

- .github/workflows/test.yml
- documentation/installing-yazi-from-source.md
- lua/yazi/process/yazi_process_api.lua
chore!: update to the latest commit of yazi
BREAKING CHANGE: If you use `use_ya_for_events_reading = true` in your
yazi.nvim config, you need to upgrade your yazi version to the currently
latest version:
> feat: new extract builtin plugin for archive extracting (#1321)
>
> https://github.com/sxyazi/yazi/commit/bce0fc1175c855ecb2dbee6f8575857b1e9616d4
@sxyazi fyi, noticed that the latest commit of yazi has some new
features and seems like `pub-to` should be used. I'm changing this in
the bleeding edge version of yazi.nvim to keep up.
> chore!: update to the latest commit of yazi

- .github/workflows/test.yml
- README.md
- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- integration-tests/test-environment/test-setup.lua
- lua/yazi/config.lua
- lua/yazi/health.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- spec/yazi/health_spec.lua
- spec/yazi/plugin_spec.lua
- spec/yazi/relative_path_spec.lua
> This feature is available both when using `ya_for_events_reading and
> without it.
>
> If you get any errors, run `:healthcheck yazi` for more information.
When yazi is open, pressing `<c-y>` will copy the relative path of the currently hovered file to the clipboard. If multiple files are selected, the relative paths of all selected files will be copied, one per line.
The relative path is calculated from the file/directory yazi was started in, so it should do the right thing in most cases.
This feature requires GNU `realpath` on Linux and `grealpath` on macOS. `grealpath` is available in the `coreutils` package on Homebrew. On most Linux systems, `realpath` should be available by default.
> feat: `<c-y>` to copy relative path to selected file(s)

- lua/yazi/config.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/utils.lua
- spec/yazi/dir_of_spec.lua
- spec/yazi/keybinding_helpers_spec.lua
Fixes a bug where grepping or replacing with `<c-s>` or `<c-g>` would pick Neovim's current working directory instead of the directory of the file.
This needs another look after https://github.com/sxyazi/yazi/issues/1314 is resolved. Maybe it can be improved.
> fix: grepping or replacing in cwd instead of the directory of the file

- integration-tests/client/testEnvironmentTypes.ts
- integration-tests/client/websocket-client.ts
- integration-tests/server/utilities/DisposeableSingleApplication.ts
- integration-tests/server/utilities/TerminalApplication.ts
Previously there was a limitation for the browser window. Only a single size worked. Other sizes would cause neovim's text not to be shown at all. Not sure why this happened, but it seems that if I pass the current size of the terminal's textarea to the server, this issue is avoided.
> test: allow different sizes for the terminal in the integration tests

- lua/yazi/lsp/embedded/lsp-file-operations/did-create.lua
- lua/yazi/lsp/embedded/lsp-file-operations/did-delete.lua
- lua/yazi/lsp/embedded/lsp-file-operations/did-rename.lua
- lua/yazi/lsp/embedded/lsp-file-operations/will-create.lua
- lua/yazi/lsp/embedded/lsp-file-operations/will-delete.lua
- lua/yazi/lsp/embedded/lsp-file-operations/will-rename.lua
`vim.lsp.get_active_clients()` is deprecated and will be removed in Neovim 0.12. This causes deprecation warning on 0.11 after renaming files with bulk renaming feature:
```console
- WARNING vim.lsp.get_active_clients() is deprecated. Feature will be removed in Nvim 0.12
- ADVICE:
- use vim.lsp.get_clients() instead.
- stack traceback:
/home/xfzv/.local/share/nvim/lazy/yazi.nvim/lua/yazi/lsp/embedded/lsp-file-operations/will-rename.lua:37
/home/xfzv/.local/share/nvim/lazy/yazi.nvim/lua/yazi/lsp/rename.lua:11
/home/xfzv/.local/share/nvim/lazy/yazi.nvim/lua/yazi/event_handling.lua:100
/home/xfzv/.local/share/nvim/lazy/yazi.nvim/lua/yazi.lua:75
/home/xfzv/.local/share/nvim/lazy/yazi.nvim/lua/yazi/process/yazi_process.lua:54
- stack traceback: …
```
> refactor: use `vim.lsp.get_clients()` instead of deprecated `vim.lsp.get_active_clients()`

- lua/yazi/window.lua
Fixes https://github.com/mikavilpas/yazi.nvim/issues/295
> fix: pressing <esc> has a 1 second delay

- integration-tests/cypress/e2e/help-menu.cy.ts
- lua/yazi/config.lua
When the help menu is open, it can now also be closed with the same key that opened the help.
> feat(help): allow closing menu with the help key

- .github/workflows/style.yml
- README.md
- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- lua/yazi/config.lua
- lua/yazi/openers.lua
- lua/yazi/types.lua
- spec/yazi/open_multiple_files_spec.lua
Opening multiple files send them to the quickfix by default.
Opening multiple files open multiple buffers.
It is unlikely the default behavior users expect when opening multiple files is to send them to the quickfix.
Selecting 3 files and pressing enter...
Open them as 3 buffers as result by default
Users who want a different behavior can still override the function in opts. This PR is just about better UX.
> ✨feat(`openers`): New opener `open_multiple_files()` is now the default value for `config.hooks.yazi_opened_multiple_files`.

- integration-tests/cypress/e2e/using-shell-redirection-to-read-events/opening-directories.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-directories.cy.ts
- lua/yazi/hijack_netrw.lua
I think this bug was introduced in 7eb5f933c863, but now it has a test and is unlikely to happen again.
> fix: not being in insert mode when opening a dir from the command line

- .github/workflows/eslint.yml
- .github/workflows/issues.yml
- .github/workflows/linkspector.yml
- .github/workflows/release-luarocks.yml
- .github/workflows/style.yml
- .github/workflows/test.yml
- .github/workflows/typecheck.yml
This might help to avoid breaking changes in the future. Dependabot will still be able to update the actions to the latest version, an example can be seen in 7062de6
> ci: use exact versions for actions

- lua/yazi/lsp/embedded/lsp-file-operations.lua
In yazi.nvim, we don't need these plugins. If the user had them in their configuration, they were being set up which required some (minimal) work to be done. This commit removes that work.
I could have removed the code entirely, but I decided to keep it in case we want to depend on the official lsp-file-operations in the future.
> perf: don't set up nvim-tree and neo-tree in lsp-file-operations

- repro.lua
The integration tests already use this colorscheme, and the colors are depended on in the tests. This change makes the reproduction script use the same colorscheme as the tests.
But the real reason is that it's my current favorite colorscheme.
> chore: reproduction script uses catppuccin instead of tokyonight

- README.md
- integration-tests/cypress/e2e/using-ya-to-read-events/hover-highlights.cy.ts
- integration-tests/server/application/neovim/testEnvironmentTypes.ts
- integration-tests/test-environment/config-modifications/notify_hover_events.lua
- lua/yazi.lua
- lua/yazi/buffer_highlighting/highlight_hovered_buffer.lua
- lua/yazi/event_handling/nvim_event_handling.lua
- lua/yazi/event_handling/yazi_event_handling.lua
- lua/yazi/process/ya_process.lua
- spec/yazi/delete_spec.lua
- spec/yazi/move_spec.lua
- spec/yazi/rename_spec.lua
- spec/yazi/trash_spec.lua
It's now possible to create a custom integration in your own configuration. This can be useful for creating custom behavior when hovering over a file in yazi. In the future, other events might be supported as well.
```lua
vim.api.nvim_create_autocmd('User', {
pattern = 'YaziDDSHover',
-- see `:help event-args`
---@param event {data: YaziHoverEvent}
callback = function(event)
vim.notify(
vim.inspect({ 'Just received a YaziDDSHover event!', event.data })
)
end,
})
```
> feat: add support for external integrations to hover events

- lua/yazi/buffer_highlighting/yazi_session_highlighter.lua
- lua/yazi/renameable_buffer.lua
- spec/yazi/renameable_buffer_spec.lua
When hovering over a directory, Yazi should highlight buffers in the same directory, not in the hovered directory.
Previously, Yazi was highlighting buffers in the hovered directory instead of the same directory, causing confusion.
> fix: highlighting siblings of hovered directories

- .github/workflows/test.yml
- README.md
- integration-tests/cypress/e2e/healthcheck.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/cd-to-buffer.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/hover-highlights.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/utils/hover-utils.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/utils/yazi-utils.ts
- integration-tests/server/application/neovim/environment/testEnvironmentTypes.ts
- integration-tests/test-environment/config-modifications/modify_yazi_config_and_open_multiple_files.lua
- integration-tests/test-environment/dir with spaces/file1.txt
- integration-tests/test-environment/dir with spaces/file2.txt
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/process/legacy_events_from_file.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- spec/yazi/selected_files_spec.lua
- spec/yazi/yazi_spec.lua
If you have multiple splits open in Neovim, yazi will now open all of them in tabs when you open yazi. This is useful when you want to perform file operations to whatever you are working on.
This feature is off by default. To enable it, you can set `open_multiple_tabs = true` in your configuration.
By default, the number keys currently switch between tabs. See all the default keybindings here:
https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml
Limitations:
- the bleeding edge yazi version from yesterday is required (https://github.com/sxyazi/yazi/commit/dac72eb39a846d15db7f1a7c54e9261675a90e53)
- yazi can only display up to 9 paths, so only the first 9 files will be opened in tabs
https://github.com/user-attachments/assets/49ed1af4-5463-401a-a328-82f486ee50a1
> feat: open currently visible splits as yazi tabs (opt-in)

- lua/yazi/process/ya_process.lua
- spec/yazi/ya_process_spec.lua
- spec/yazi/yazi_spec.lua
- spec/yazi/yazi_visible_buffer_spec.lua
Problem:
With a split window setup of two files (a and b) like this `a|a|b`, when the split `b` was focused, yazi.nvim would open 3 yazi tabs instead of 2.
Solution:
Add a function to remove duplicates from the list of files to open.
> fix: don't open duplicate tabs when opening files

- lua/yazi.lua
- plugin/yazi.lua
- spec/yazi/lazy_loading_spec.lua
It might help users that don't use lazy.nvim by making the initialization slightly easier. An example is possibly the following issue:
https://github.com/mikavilpas/yazi.nvim/issues/340
> feat: allow using :Yazi commands automatically by default

- Makefile
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-directories.cy.ts
- integration-tests/package.json
- integration-tests/server/neovim/environment/testEnvironmentTypes.ts
- integration-tests/test-environment/config-modifications/add_command_to_count_open_buffers.lua
- lua/yazi/hijack_netrw.lua
- package-lock.json
When opening a directory with `:edit .`, yazi.nvim would open an empty
buffer for technical reasons. This empty buffer would show up in the
user's neovim session, and would be counted as an open buffer.
> fix: leaving an empty buffer when opening a directory with `:edit .`

- .luarc.json
It was released yesterday, but was toggled off by default. The example in the pull request works nicely.
- pull request
- https://github.com/LuaLS/lua-language-server/pull/2768
- comment saying why it was toggled off
- https://github.com/LuaLS/lua-language-server/pull/2768#issuecomment-2293094921
- changelog with a little more info
- https://github.com/LuaLS/lua-language-server/blob/d702a55715df19a219e963da496e6fb76db0aacd/changelog.md?plain=1#L8
> chore: enable lua-language-server `checkTableShape` by default

- lua/yazi/renameable_buffer.lua
- lua/yazi/utils.lua
- spec/yazi/dir_of_spec.lua
- spec/yazi/keybinding_helpers_spec.lua
Issue:
Given the following directory structure:
- root/
- dir1/
- file1
- file2
When hovering `dir1/` and starting the search or replace operation, the operation would only consider the files in `dir1/`. This is not what the user would expect. The user would expect the operation to consider the files in `root/`.
Solution:
When hovering a directory, we should consider the directory the hovered directory is in. This is the same behavior as when hovering a file.
> fix: starting telescope or grug-far when hovering a directory

- lua/yazi/buffer_highlighting/window_highlight.lua
Problem:
When highlighting a buffer that's hovered in yazi, or highlighting a buffer that's in the same directory as the hovered file, the background color is not found, and the highlighting is not applied. However, the error message is also shown to the user.
I originally intended this to be a "this should never happen" kind of error, but it's not the case. It is also shown if the user is using a transparent background with a plugin like "xiyaowong/transparent.nvim".
See here for the exact configuration that causes this issue: https://github.com/mikavilpas/yazi.nvim/issues/392#issuecomment-2295345115
> I use tokyonight theme and "xiyaowong/transparent.nvim" plugin to
> toggle transparency
>
> https://github.com/xiyaowong/transparent.nvim
Solution:
Remove the error message, and let the …
> fix: showing error message when background color is not found

- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- lua/yazi/event_handling/yazi_event_handling.lua
Problem:
When a file is trashed (moved to the trash) or deleted (hard deleted) in yazi, the buffer associated with the file is deleted. However, if the buffer is modified, the buffer cannot be deleted. This is because the buffer has unsaved changes.
Solution:
Force delete the buffer when it is being deleted, losing any unsaved changes.
Originally I wanted to make sure no unsaved changes are lost, but I noticed neo-tree does not care about unsaved changes when deleting a file, so I decided to follow the same behavior.
Solves https://github.com/mikavilpas/yazi.nvim/issues/397
> fix: not being able to delete a buffer when it is modified

- integration-tests/cypress/e2e/using-ya-to-read-events/opening-directories.cy.ts
- lua/yazi/hijack_netrw.lua
Problem:
When the user had two or more split windows open and opened a directory in yazi, the current split window was closed. The buffer was not closed, however, and the user could still see the buffer in the buffer list.
This is an annoying side effect that serves no real purpose.
Solution:
Don't close the current split window when opening a directory in yazi.
> fix: closing split when opening directory

- lua/yazi/openers.lua
- spec/yazi/file_openers_spec.lua
In yazi.nvim, it's possible to open files in new splits (horizontal and vertical) and tabs.
Issue: when opening a directory in a split or tab, and when the setting open_for_directories is set to true, the directory would be opened in a new floating yazi window, and a useless split or tab would be opened with the currently open buffer.
Solution: check if the chosen file is a directory before opening it in a split or tab. If it's a directory, don't open it in a split or tab (do nothing).
> fix: opening directories in splits and tabs opening empty buffers

- .github/workflows/linkspector.yml
- integration-tests/package.json
- lua/yazi/hijack_netrw.lua
- lua/yazi/window.lua
- package-lock.json
Issue
=
When opening yazi with `nvim .`, an extra `i` key was sent yazi. If the
user had set up a custom mapping for `i` in their yazi config, it would
be triggered when opening yazi with `nvim .`. In other cases this bug
would not get triggered.
Solution
=
Check if we're in the situation where the `i` key needs to be pressed
(to enter insert mode) and only then send the key.
> fix: `nvim .` sent extra `i` key to yazi

- lua/yazi/config.lua
- spec/yazi/grug_far_spec.lua
Last week in https://github.com/MagicDuck/grug-far.nvim/pull/233 the main function was renamed from `grug_far` to `open`. This commit updates the code to use the new function name.
> refactor: adapt to grug-far deprecation

- lua/yazi.lua
- lua/yazi/types.lua
- spec/yazi/yazi_spec.lua
This was a leftover from the initial implementation of the plugin, and is no longer used for anything.
> refactor: remove events_file_path config option (unused)

- lua/yazi/hijack_netrw.lua
Issue
=
In the following scenario, when all of these happened, yazi would always open when restoring a session:
- When using LazyVim / folke/persistence.nvim
- start neovim with `nvim .`
- open a file
- close neovim
- start neovim with `nvim`
- restore the last session with persistence.nvim
This seemed to happen because the session includes the `.` which was given as an argument to neovim. Restoring the session would open the directory in yazi.
Solution
=
The solution is to check if the `SessionLoad` variable is set to `1` and skip opening yazi if it is. This is because the `SessionLoad` variable is set to `1` when restoring a session.
See `:h SessionLoad-variable` for more information.
Fixes https://github.com/mikavilpas/yazi.nvim/issues/440
> fix: opening a LazyVim session with folke/persistence.nvim starting yazi

- integration-tests/cypress.config.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/cd-to-buffer.cy.ts
- lua/yazi/keybinding_helpers.lua
Issue
=====
Using `tab` to cycle through open buffers does not work when only one buffer is open. I disabled it because I thought it was not useful in that case, but actually it can still be useful in the following case:
- you have opened yazi and have a single buffer open in neovim (no splits)
- you have navigated to a different directory in the file explorer
- you have gotten lost
- you want to get back to the beginning with `tab`
Solution
========
Enable `tab` to cd to the single buffer's directory.
Solves https://github.com/mikavilpas/yazi.nvim/issues/447
> feat: allow cycle_open_buffers (`tab`) to work for a single file

- .github/workflows/lint.yml
- .github/workflows/test.yml
- integration-tests/package.json
- lua/yazi/config.lua
- package-lock.json
Issue
=====
If the user has set up custom autocmds that trigger for `help` buffers, the yazi.nvim help popup buffer will be affected by them. I noticed this after setting the following autocmd:
```lua
vim.api.nvim_create_autocmd("FileType", {
-- always open help buffers in a vertical split
pattern = { "help", "man" },
command = "wincmd L",
})
```
Solution
========
Only use the `syntax` option to set the filetype of the help buffer to `help`. This way, the user's custom autocmds will not affect the help popup buffer.
> fix: avoid custom autocmd conflicts with the help popup buffer

- integration-tests/package.json
- lua/yazi/types.lua
- lua/yazi/window.lua
- package-lock.json
Now you can have e.g. a wide screen yazi.nvim experience by setting
`floating_window_scaling_factor = { width = 0.95, height = 0.70 }` in
your configuration 😄
> feat: allow scaling the floating window width and height separately

- lua/yazi.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/process/yazi_process_api.lua
- lua/yazi/types.lua
- spec/yazi/ya_process_spec.lua
This is a technical change that allows keybindings to access the current working directory of the ya process. It can be used to solve https://github.com/mikavilpas/yazi.nvim/issues/466 in the future
> feat: expose the current working directory to keybindings

- .prettierignore
- integration-tests/package.json
- pnpm-lock.yaml
```sh
◉ @catppuccin/palette                1.3.0  →   1.4.0
◉ @tui-sandbox/library               1.0.5  →   1.2.0
◉ @typescript-eslint/eslint-plugin   8.5.0  →   8.6.0
◉ @typescript-eslint/parser          8.5.0  →   8.6.0
◉ eslint                            9.10.0  →  9.11.0
◉ nodemon                            3.1.4  →   3.1.7
◉ prettier-plugin-organize-imports   4.0.0  →   4.1.0
◉ vite                               5.4.6  →   5.4.7
```
> chore: update all dependencies to newest versions

- lua/yazi/keybinding_helpers.lua
- spec/yazi/keybinding_helpers_spec.lua
1. I found a bug when trying to change cwd on startup, in which since ya process have not logged anything yet, `context.ya_process.cwd` is `nil`, making the function ineffective. Therefore,  I implement it so it uses input_path in this case. 
2. I modified the conditional to check if the `last_directory` equals cwd when the function is called, in which cwd does not need to be changed.
> fix: use input dir if needed when changing cwd

- lua/yazi/event_handling/nvim_event_handling.lua
- lua/yazi/process/ya_process.lua
- spec/yazi/ya_process_spec.lua
Problem
=======
When files are renamed or moved in yazi, there is no way for other plugins to know about this. If the user uses yazi.nvim along with other plugins that need to react to files being renamed or moved, it cannot be done. This means that other plugins that depend on yazi cannot react to these changes.
Currently yazi.nvim can only react to LSP delete/rename events, but plugins that operate outside of the LSP protocol are not supported.
Solution
========
Add a new Neovim autocmd/event called `YaziRenamedOrMoved` that is emitted when files are renamed or moved. This event will contain a table of the paths that were renamed or moved.
Previously we were already emitting a Neovim event for `YaziDDSHover` - now we have two custom events.
Closes …
> feat: emit YaziRenamedOrMoved event when files are renamed or moved

- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- integration-tests/test-environment/config-modifications/notify_rename_events.lua
- lua/yazi/event_handling/nvim_event_handling.lua
- lua/yazi/process/ya_process.lua
- spec/yazi/ya_process_spec.lua
Issue
=====
When a file was renamed/moved, a YaziRenamedOrMoved event was supposed to be published. However, the event was not actually published in practice due to `E5560: nvim_exec_autocmds must not be called in a lua loop callback`.
Solution
========
The solution was to schedule the event publishing in a `vim.schedule` block. This way, the event publishing is deferred to the next event loop iteration, which avoids the error.
For some reason, this error is not visible in unit tests, so I added an integration test to make sure it doesn't break again.
> fix: YaziRenamedOrMoved events could not be published in practice

- documentation/installing-yazi-from-source.md
The `--locked` flag tells Cargo to use the exact dependencies specified in the Cargo.lock file, without attempting to update them.
> docs: add `--locked` flag to "installing-yazi-from-source" commands

- .github/workflows/lint.yml
- .github/workflows/style.yml
Issue
=====
Currently these jobs run when a pull_request is created or updated:
```text
Linkspector / runner / linkspector (pull_request) Successful in 2m
Linting / markdownlint (pull_request) Successful in 4s
Linting / markdownlint (push) Successful in 3s
Linting / selene (pull_request) Successful in 4s
Linting / selene (push) Successful in 3s
LuaRocks release / LuaRocks upload (pull_request) Successful in 28s
Run tests / Run tests (nightly) (pull_request) Successful in 2m
Run tests / Run tests (stable) (pull_request) Successful in 2m
Style checking / prettier (pull_request) Successful in 32s
Style checking / prettier (push) Successful in 29s
Style checking / stylua (pull_request) Successful in 3s
Style checking / stylua (push) Successful in 3s
Type check / Type check (pull_request) …
```
> ci: don't run lint and style checks on push events

- lua/yazi.lua
- spec/yazi/helpers/test_files.lua
- spec/yazi/yazi_spec.lua
Background
==========
When yazi is started too late, it can happen that we don't know what the
last_directory was when yazi has exited. When this happens, yazi has
already reported its `cd` event before `ya` starts and yazi.nvim cannot
capture it.
The issue can be tracked in https://github.com/sxyazi/yazi/issues/1314
Issue
=====
Currently yazi.nvim works around this limitation by using the parent
directory of the input_path as the last_directory since it's a good guess.
However, it looks like this has never worked reliably due to a bug in the
implementation. The correct directory was calculated, but it was not
assigned to the last_directory field in the state - it was ignored and
had no effect.
Solution
========
Assign the correct directory to the last_directory field in the state.
> fix: report parent directory of input_path as last_directory

- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- integration-tests/test-environment/config-modifications/modify_yazi_config_log_yazi_closed_successfully.lua
- lua/yazi.lua
- lua/yazi/event_handling/yazi_event_handling.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/process/yazi_process.lua
- spec/yazi/helpers/fake_yazi_process.lua
- spec/yazi/yazi_spec.lua
Background
==========
The `last_directory` is the last directory that yazi was in before it was closed. This is useful for various custom integrations that users might want to do with yazi.
Issue
=====
The `last_directory` variable seemed to always be empty. It used to work, but I think it broke when I added the following commit some time ago:
> feat: expose the current working directory to keybindings (#471)
>
> https://github.com/mikavilpas/yazi.nvim/commit/445f4877d8b80f9d24ea1f9b890c878211878d63
The `last_directory` variable is being set currently, but using it still depends on the old implementation that was in effect before the commit above - it basically cannot be found because it's still expected to be in the old place.
Solution
========
Use the new implementation that was …
> fix: not being able to resolve the last_directory

- lua/yazi/process/yazi_process.lua
- spec/yazi/ya_process_spec.lua
Expose the current working directory as `NVIM_CWD` so that yazi keybindings can use it to offer basic neovim specific functionality when running yazi inside neovim with yazi.nvim.
Reference: https://github.com/mikavilpas/yazi.nvim/issues/547
> feat: allow using nvim's cwd in yazi keybindings

- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- integration-tests/cypress/support/commands.ts
- integration-tests/test-environment/.config/yazi/keymap.toml
- integration-tests/test-environment/config-modifications/notify_custom_events.lua
- lua/yazi/event_handling/nvim_event_handling.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
> note: DDS means "Data Distribution Service". It's a way for yazi to
> communicate with neovim and other processes.
>
> https://yazi-rs.github.io/docs/dds
Issue
=====
Yazi is incredibly versatile and can be used for many different things.
However, it's too difficult to predict what the needs of every user will
be. Power users have no easy way to extend the behaviour of yazi.nvim
beyond the features that are built-in.
Solution
========
Allow users to subscribe to custom yazi DDS events. These events are
possibly not included in yazi by default, but can be published by yazi
plugins or by other applications using yazi's DDS system.
By default, all custom events are ignored. The user can specify which
events they want to listen to by setting a new `forwarded_dds_events`
(string[], default …
> feat: support reacting to custom yazi DDS events

- .github/workflows/eslint.yml
- README.md
- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- integration-tests/cypress/support/tui-sandbox.ts
- integration-tests/package.json
- integration-tests/test-environment/.config/nvim/init.lua
- lua/yazi/event_handling/yazi_event_handling.lua
- lua/yazi/utils.lua
- package.json
- pnpm-lock.yaml
Issue
=====
When yazi deletes a file, yazi.nvim also closes that buffer. However,
the default implementation in neovim is to also close the window/split
if one is currently open. This is distracting and annoying for users
(me).
Solution
========
If the https://github.com/folke/snacks.nvim plugin is installed,
yazi.nvim uses that to delete the buffer while preserving the window
layout.
If it's not installed, the old (annoying) behavior is used.
In the future, snacks.nvim might come a required dependency for
yazi.nvim.
> feat: using folke/snacks.nvim can preserve window layouts on deletes

- .github/workflows/test.yml
- README.md
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/cd-to-buffer-with-ya-emit.cy.ts
- integration-tests/test-environment/config-modifications/modify_yazi_config_use_ya_emit.lua
- integration-tests/test-environment/highlights/file_1.txt
- integration-tests/test-environment/highlights/file_2.txt
- integration-tests/test-environment/highlights/file_3.txt
- lua/yazi/config.lua
- lua/yazi/health.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/process/yazi_process_api.lua
- lua/yazi/types.lua
- spec/yazi/health_spec.lua
- spec/yazi/keybinding_helpers_spec.lua
To celebrate the release of yazi 0.4.0, you can now opt in to improve the accuracy of `<tab>` to a file. Read below for more information on what this is and how you can opt into using it.
https://github.com/sxyazi/yazi/releases/tag/v0.4.0
Background
==========
When yazi is open, and there are multiple splits open in neovim, it's currently possible to press `<tab>` to cycle through the open buffers. When you press `<tab>`, yazi will change its current directory and focus the file that's next in the list of open splits (vertical or horizontal split).
Issue
=====
When pressing `<tab>`, yazi was only able to change its current directory to the same directory the next split is in. If there were multiple files in that directory, the first file would be focused. This is not necessarily the file …
> feat: can use `ya emit` for more accurate <tab> to file (opt-in)

- .github/workflows/test.yml
It includes this important fix
- https://github.com/mikavilpas/yazi.nvim/issues/603
For the full release notes, see
- https://github.com/sxyazi/yazi/releases/tag/v0.4.1
> ci: use yazi v0.4.1 in integration-tests

- .github/workflows/test.yml
- README.md
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/using-ya-to-read-events/integrations.cy.ts
- integration-tests/test-environment/.config/nvim/init.lua
- integration-tests/test-environment/config-modifications/modify_yazi_config_use_fzf_lua.lua
- lua/yazi/config.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/types.lua
- spec/yazi/keybinding_helpers_spec.lua
Previously, it was only possible to use Telescope to grep (search for
text) in files and directories. This commit adds support for using
fzf-lua.nvim.
The default continues to be Telescope, but users can now set the
following values to opt into using fzf-lua:
```lua
---@type YaziConfig
{
-- ... other settings
integrations = {
grep_in_directory = "fzf-lua",
grep_in_selected_files = "fzf-lua",
},
}
```
> feat: add fzf-lua integration for grepping in files and dirs

- documentation/yazi-keymappings.md
- integration-tests/test-environment/.config/yazi/keymap.toml
This was deprecated in yazi 0.4.0 which was released 2024-12-08.
https://github.com/sxyazi/yazi/pull/1982
> docs: avoid recommending --confirm in keymap.toml examples

- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- lua/yazi/window.lua
When a file was opened in a new tab, and then an existing buffer was switched to in the new tab, the buffer would not display line numbers.
https://github.com/mikavilpas/yazi.nvim/issues/649
> fix: preserve line numbers when switching buffers in a new tab

- .github/workflows/test.yml
- integration-tests/MyTestDirectory.ts
- integration-tests/package.json
- integration-tests/test-environment/.config/nvim/prepare.lua
- pnpm-lock.yaml
This allows sharing the plugin installation logic between development
and ci.
https://github.com/mikavilpas/tui-sandbox/pull/225
> test: use tui-sandbox's prepare.lua to install plugins before tests

- README.md
- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- integration-tests/test-environment/.config/nvim/init.lua
- lua/yazi/utils.lua
- package.json
If you select a file path in visual mode and then press your yazi
keymapping, yazi will open and hover the file at that path.
How is this useful?
- sometimes you don't want to open a file in neovim because it will
start LSP servers, other plugins, or other things that you don't need
for your task
- you want to use yazi to move or rename the file, or copy its contents
NOTE: To use this feature, you will need to add a visual mode mapping
for yazi. You can find an example of this for lazy.nvim in the README
file.
> feat: open yazi, hovering the visual selection file path

- lua/yazi/health.lua
On Neovim nightly, `vim.fn.executable` requires a non-nil argument.
> fix(health): verify resolver is set

- .github/workflows/style.yml
- .github/workflows/test.yml
This might help speed up the jobs a bit, although it has not been an issue so far.
> ci: follow pnpm/action-setup's cache usage instructions

- .github/workflows/eslint.yml
- .github/workflows/style.yml
- .github/workflows/test.yml
It seems to have some issues right now, and it has not produced a lot of value. Let's opt for a simpler approach for now.
> ci: run eslint without reviewdog to avoid complexity

- lua/yazi/keybinding_helpers.lua
- lua/yazi/types.lua
This simplifies the implementation of the `grep_in_selected_files` integrations, as currently they will need to copy paste code to implement the most common use case (using relative_paths).
Solves https://github.com/mikavilpas/yazi.nvim/issues/703
> refactor: provide relative paths to grep_in_selected_files

- integration-tests/cypress/e2e/using-ya-to-read-events/opening-files.cy.ts
- lua/yazi/utils.lua
When a relative file path is selected in visual mode, yazi should open the file relative to the current file. It was opening the file relative to the current working directory instead.
> fix: opening files from visual mode did not work for relative paths

- README.md
- integration-tests/test-environment/.config/nvim/init.lua
- lua/yazi/config.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
Issue
=====
Some yazi events are processed only when yazi exits. These include the following events:
- `rename` (a file was renamed)
- `bulk` (files were renamed using yazi's bulk rename feature)
- `move` (a file was moved)
- `delete` (you guessed it, a file was deleted)
The reason for this is that at the time I added support for handling these event types, yazi was not yet able to provide event information before it was completely closed.
Solution
========
Add a new configuration option, `process_events_live`, which defaults to `false` for now. When this option is `true`, all event types are processed as soon as possible.
It's recommended to add the https://github.com/folke/snacks.nvim plugin so that yazi.nvim can use it to delete buffers. By default, Neovim closes split windows when a …
> feat: allow processing all yazi events as soon as possible

- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- lua/yazi/utils.lua
Issue
=====
When renaming a file to a new name and back to its old name (a->b->a), the buffer/split is closed after the second rename.
This is caused by the buffer remaining as an unlisted buffer after the first rename. When the buffer is renamed back to its original name, the code thought that the buffer was already open and closed it.
Solution
========
Don't consider unlisted buffers as open buffers, avoiding the problem.
> fix: renaming a file to its old name closed the buffer

- lua/yazi.lua
- lua/yazi/event_handling/yazi_event_handling.lua
- lua/yazi/process/ya_process.lua
refactor: remove extra vim.schedule in ya_process
refactor: assert events aren't processed twice
> refactor: combine rename/move event handling into a single function

- integration-tests/cypress/e2e/using-ya-to-read-events/toggling.cy.ts
- lua/yazi.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/process/yazi_process_api.lua
- spec/yazi/helpers/fake_yazi_process.lua
- spec/yazi/ya_process_spec.lua
Issue
=====
When using `:Yazi toggle` after previously having hovered a directory, yazi is reopened hovering the contents of the directory instead of the directory itself.
Solution
========
Wait for yazi to start, and use `ya reveal` to make yazi focus on the directory. This takes 50-100ms of time which is very slightly janky, but it's much better to have an 80% solution than a 0% solution.
Closes https://github.com/mikavilpas/yazi.nvim/issues/727
> fix: `:Yazi toggle` not being able to hover a directory

- .github/workflows/test.yml
https://github.com/sxyazi/yazi/releases/tag/v25.2.7 is out, let's test against that!
> ci: bump the integration-tests yazi version from v0.4.2 to v25.2.7

- integration-tests/cypress/e2e/using-ya-to-read-events/reading-events.cy.ts
- integration-tests/eslint.config.mjs
- integration-tests/package.json
- pnpm-lock.yaml
Issue
=====
Eslint cannot be run after a clean install.
```sh
[Running: fd node_modules --no-ignore --prune -x rm -rf && pnpm i && cd integration-tests && pnpm eslint]
Scope: all 2 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +607
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 607, reused 607, downloaded 0, added 607, done
devDependencies:
+ @umbrelladocs/linkspector 0.3.13
+ markdownlint-cli2 0.17.2
+ prettier 3.4.2
+ prettier-plugin-organize-imports 4.1.0
+ prettier-plugin-packagejson 2.5.8
Done in 4.8s
> @yazi.nvim/integration-tests@0.0.0 eslint …
```
> chore(eslint): migrate eslint to avoid pnpm dep hoisting issue

- README.md
- repro.lua
The yazi version in the comment has been stable for around 6 months, so
it should be very safe to remove.
- vim.loop has been deprecated in neovim 0.10.0
https://github.com/neovim/neovim/blob/c7d13f2895fa657ff3d9d45741f9abec25072b56/runtime/doc/deprecated.txt#L113
- `:Yazi toggle` has been stable for around 6 months
> Refactoring

- lua/yazi/process/ya_process.lua
- lua/yazi/utils.lua
Closes https://github.com/mikavilpas/yazi.nvim/issues/744
> fix: not being able live delete buffers without snacks.bufdelete

- README.md
- lazy.lua
- lua/yazi.lua
- repro.lua
Issue
=====
When using lua_ls types, the lua LSP would complain when using the public yazi functions. They were meant to allow passing a partial YaziConfig, but the type definition required everything to be present.
The behaviour is that any overrides to the default config are used when calling the apis.
Solution
========
Allow passing a partial YaziConfig to the public functions.
> refactor(types): correctly allow passing a partial YaziConfig

- README.md
- integration-tests/test-environment/.config/nvim/init.lua
- lazy.lua
- lua/yazi/config.lua
- lua/yazi/types.lua
BREAKING CHANGE: This change now requires
https://github.com/folke/snacks.nvim to be installed. Users of [lazy.nvim](https://lazy.folke.io/) and
[rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) should have this dependency automatically installed.
About a month ago, `process_events_live=false` was introduced an an opt-in feature in https://github.com/mikavilpas/yazi.nvim/pull/718. It allows processing yazi events, such as file renames, immediately instead of in a batch when yazi is closed.
If you are unable to install snacks.nvim, you can still disable this feature for some time by setting `future_features.process_events_live = false` in your yazi.nvim configuration, so that you have some time to migrate. See the README for more information.
> feat!: process yazi events live by default (requires snacks.nvim)

- README.md
As per [Release 8.0](https://github.com/mikavilpas/yazi.nvim/pull/770), [snacks.nvim](https://github.com/folke/snacks.nvim) is now a required dependency for usage of `process_events_live` therefore this PR adds this information in `README` to accomodate users not using `lazy.nvim` or `rocks.nvim`.
> docs: add note about snacks.nvim dependency as per 8.0

- README.md
Adding it explicitly is optional if you're using lazy.nvim and maybe also for rocks.nvim, but it's a good idea to make it very clear that it's a dependency for users.
Closes https://github.com/mikavilpas/yazi.nvim/issues/774
> docs: clarify that snacks is a dependency

- integration-tests/cypress/e2e/opening-files.cy.ts
This is faster and maybe less annoying to maintain over the long run.
> test: preselecting a file with spaces in the path

- .github/workflows/test.yml
- integration-tests/package.json
- lua/yazi/event_handling/nvim_event_handling.lua
- lua/yazi/event_handling/yazi_event_handling.lua
- pnpm-lock.yaml
- spec/yazi/ya_process_spec.lua
fix: publishing move events to other nvim plugins
It would silently crash when trying to publish move events to other nvim
plugins. I don't think this is a huge issue since the feature does not
seem to be widely used.
It might be that it never actually worked for move events, but did work
for rename and bulk events.
For a description of this event publishing feature, see
https://github.com/mikavilpas/yazi.nvim/pull/495
> fix: publishing move events to other nvim plugins

- README.md
- integration-tests/cypress/e2e/opening-files.cy.ts
- lua/yazi/utils.lua
- pnpm-lock.yaml
Issue
=====
The quickfix list is a versatile tool in neovim, and it can be used for
many different workflows.
yazi.nvim can send files from yazi to the quickfix list, but when this
is done, yazi is closed and the context is lost. When doing project wide
work both in yazi and neovim, it's difficult because of this.
Solution
========
Allow opening yazi tabs for the files in the quickfix list. This only
works if the user has enabled the `open_multiple_tabs` setting.
Otherwise the first quickfix file is selected.
When the quickfix list is open and focused, opening yazi will now open
(probably) 9 of the first files as yazi tabs. The limitation is in place
because yazi can open up to 9 tabs at a time.
> feat: open yazi tabs for the files in the quickfix list

- lua/yazi/config.lua
Neovim 0.11 supports configuring floating window borders for all plugins centrally with the "winborder" setting. If this is set, it is used by default. Otherwise the previous behaviour is preserved.
https://github.com/neovim/neovim/pull/31074
> feat: support `winborder` setting on Neovim nightly (0.11+)

- lua/yazi.lua
- lua/yazi/utils.lua
- spec/yazi/relative_path_spec.lua
Sometimes when using vertical splits, I noticed that when yazi is
closed, one of the splits switches to a different buffer. I was unable
to reproduce this issue consistently, but I have had this happen every
once in a while for the last two weeks.
It seems like I added some logic to on_yazi_exited that restores the
previous buffer, but I don't think that's necessary - it does not seem
to be doing anything.
I'm hoping this will resolve the issue and not cause any (untested)
features to break, but I think it should be quite safe.
Did not cause any issues though
> fix: don't restore the previous buffer when yazi is closed

- lua/yazi/config.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/types.lua
BREAKING CHANGE: If you're using an old nightly Neovim version (older than 2 months) and cannot open yazi.nvim after this, you should update your nightly Neovim. If that is not possible, you can set `future_features.use_nvim_0_10_termopen=true` in your config to work around the issue. I will keep that around for a while, but eventually it might be removed.
Some background information:
This was introduced in
- https://github.com/neovim/neovim/pull/31343 (Dec 19, 2024)
- https://github.com/mikavilpas/yazi.nvim/pull/652 (Jan 6, 2025)
But then it produced issues due to outdated nightly versions that were fixed here
- https://github.com/mikavilpas/yazi.nvim/pull/696 (Jan 23, 2025)
The workaround was originally copied from
https://github.com/ibhagwan/fzf-lua/issues/1732#issuecomment-2601200097 …
> refactor!: remove 0.11 nightly termopen fallback logic

- integration-tests/cypress/e2e/opening-files.cy.ts
- lua/yazi/openers.lua
That command should duplicate the first line (`:t` is the same as `:copy`)
Closes https://github.com/mikavilpas/yazi.nvim/issues/857
> fix: quickfix items not being processable with `:cfdo 1t1`

- README.md
- repro.lua
Issue
=====
Lazy loading snacks.nvim causes the following error:
```vim
:checkhealth snacks
- ⚠️ WARNING `snacks.nvim` should not be lazy-loaded. Add `lazy=false` to the plugin spec
```
This has caused issues for at least one user (see the issue below).
Solution
========
Don't lazy load snacks and avoid the error.
Closes https://github.com/mikavilpas/yazi.nvim/issues/866
> docs: remove recommendation for lazy loading snacks.nvim

- integration-tests/cypress/support/tui-sandbox.ts
- integration-tests/package.json
- lua/yazi/hijack_netrw.lua
- lua/yazi/window.lua
- pnpm-lock.yaml
This was introduced in https://github.com/mikavilpas/yazi.nvim/pull/321
but has caused issues. Sometimes neovim sends the `i` keypress to yazi,
and if the user has a mapping for this key, it will be triggered.
Try to work around this issue by sending the `i` keypress earlier.
Closes https://github.com/mikavilpas/yazi.nvim/issues/809
> fix: sending `i` on startup activating yazi actions

- integration-tests/test-environment/.config/yazi/keymap.toml
In the pr below, I tried to fix a bug where yazi.nvim would send `i` to yazi.
https://github.com/mikavilpas/yazi.nvim/pull/876
This commit adds a yazi keymap for `i` to test that it's not sent. Sending it would cause yazi to exit, which would fail any test that expects yazi to be running.
> test: force test yazi to exit with `i` to test it's not sent

- lua/yazi.lua
- lua/yazi/process/yazi_process.lua
Previously it was constructed in the yazi function, which is perhaps needlessly complicated.
> refactor: get YaziActiveContext from YaziProcess:start

- integration-tests/cypress/e2e/cd-to-buffer-with-ya-emit.cy.ts
- integration-tests/cypress/e2e/utils/yazi-utils.ts
- integration-tests/cypress/e2e/yazi-keymappings.cy.ts
- integration-tests/test-environment/.config/yazi/keymap.toml
- integration-tests/test-environment/config-modifications/notify_custom_events.lua
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/event_handling/yazi_event_handling.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
Issue
=====
By default, the `<tab>` key in yazi.nvim is used to cycle through the
open buffers. This is done in a way that prevents using the `<tab>` key
for any yazi actions.
Most of the time this does not cause issues, but in some cases the
`<tab>` key is very important. For example, if a subshell is opened in
yazi using this mapping:
```toml
[manager]
keymap = {
{ on = [":"], run = "shell 'fish' --block --confirm" }
}
```
(https://github.com/mikavilpas/dotfiles/blob/96f734f27f449783b0a1884623e27fc567849d50/.config/yazi/keymap.toml?plain=1#L116)
In this case, the subshell has no access to the `<tab>` key. For example,
this disables tab completion in the user's shell.
Solution
========
Allow users to work around this by manually defining a yazi keymap that
sends an event to yazi.nvim. …
> feat: allow a yazi keymap to cycle through open buffers

- lua/yazi/types.lua
- lua/yazi/utils.lua
- spec/yazi/delete_spec.lua
- spec/yazi/read_events_spec.lua
- spec/yazi/rename_spec.lua
- spec/yazi/trash_spec.lua
- spec/yazi/ya_process_spec.lua
They are not used for anything and are not needed.
> refactor: don't parse and store dds event timestamps

- lua/yazi/hijack_netrw.lua
Hi, I like using yazi with the `open_for_directories` setting, but netrw is still needed for handling opening files with protocols like scp, ftp, etc. I'm not sure if this is the best way to fix this, but I just added some logic to check whether the filename corresponding to the buffer contains `://` which would be in a transfer protocol that netrw should handle.
For example, opening a file such as `scp://user@server//path/to/file.txt` should not use yazi, since this would just open yazi in the cwd that your local nvim has.
> Don't hijack when using a protocol netrw should handle

- .github/workflows/test.yml
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/cd-to-buffer-with-ya-emit.cy.ts
- integration-tests/cypress/e2e/hover-highlights.cy.ts
- integration-tests/cypress/e2e/opening-files.cy.ts
- integration-tests/cypress/e2e/reading-events.cy.ts
- integration-tests/cypress/e2e/toggling.cy.ts
- integration-tests/cypress/e2e/utils/hover-utils.ts
- integration-tests/cypress/e2e/utils/yazi-utils.ts
- integration-tests/cypress/e2e/yazi-keymappings.cy.ts
- integration-tests/test-environment/config-modifications/add_command_to_reveal_a_file.lua
- integration-tests/test-environment/config-modifications/add_yazi_context_assertions.lua
- lua/yazi.lua
- lua/yazi/event_handling/yazi_event_handling.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- package.json
- spec/yazi/ya_process_spec.lua
It looks like sometimes it takes a bit longer for yazi or ya to start up
and be ready to accept commands. This can cause issues in the
integration-tests which use yazi very fast after starting it up.
This commit applies these fixes:
- prevent errors from using `vim.system():wait()` in fast events. This
is disallowed in neovim but can happen randomly with timing issues.
- toggle yazi to focus on the first file only after `ya` has
successfully received its first output. This seems to be the most
reliable way to detect when yazi is ready to accept commands. I added
support for internally listening to the `hey` event, which is emitted
when yazi acknowledges the connection from ya. This seems to occur
immediately after ya has started.
- increase the timeout for the `reveal` command to 15 …
> ci: bump yazi to latest nightly

- README.md
- lua/yazi/config.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/types.lua
- package.json
This is a follow-up to https://github.com/mikavilpas/yazi.nvim/pull/847
where this was toggled off by default.
Reasoning:
- It is 3 neovim releases old based on the date of the PR that added it
(https://github.com/neovim/neovim/pull/31343)
- I don't see anyone using this
https://github.com/search?q=use_nvim_0_10_termopen&type=code
> refactor!: remove nvim-0.10 termopen fallback completely

- integration-tests/cypress.config.ts
It can hide important details about the test run.
> test: disable yazi.nvim log truncation in test output

- .github/workflows/test.yml
When emitting an event, `ya pub` and `ya emit` now check that the receiver yazi is present as well as has the ability to receive the event that is being sent.
- https://github.com/sxyazi/yazi/issues/2680#event-17459001261
- https://github.com/sxyazi/yazi/pull/2697
> ci: bump yazi to include `ya pub/emit` checks

- integration-tests/cypress/e2e/hover-highlights.cy.ts
- integration-tests/cypress/e2e/utils/hover-utils.ts
- lua/yazi/buffer_highlighting/window_highlight.lua
- lua/yazi/keybinding_helpers.lua
- lua/yazi/process/yazi_process_api.lua
Issue
=====
After `:Yazi cwd`, the `tab` keybinding (for `cycle_open_buffers`) does
nothing.
The old implementation of cycling buffers depended on the initial file
that was opened - it was incorrectly presumed that the buffer is one of
the currently open buffers. This is not true when opening a directory.
Solution
========
Pick the first window as the initial target (the buffer to switch focus
to) when `:Yazi cwd` is used.
Closes https://github.com/mikavilpas/yazi.nvim/issues/914
> fix: not being able to cycle buffers with `tab` after `:Yazi cwd`

- README.md
- lua/yazi/health.lua
---
Mentioned in https://github.com/mikavilpas/yazi.nvim/issues/919
> Clarify that Neovim 0.11.0 or later is required

- integration-tests/cypress.config.ts
- integration-tests/cypress/e2e/cd-to-buffer-with-ya-emit.cy.ts
- integration-tests/cypress/e2e/hover-highlights.cy.ts
- integration-tests/cypress/e2e/opening-files.cy.ts
- integration-tests/cypress/e2e/reading-events.cy.ts
- integration-tests/cypress/e2e/toggling.cy.ts
- integration-tests/cypress/e2e/yazi-keymappings.cy.ts
Should reduce test flakiness - sometimes yazi and ya take a bit longer to start up. We don't want to start executing the test actions in these cases, because the results are unpredictable.
> test: poll for yazi readiness and hover states

- lua/yazi.lua
- lua/yazi/process/retry.lua
- spec/yazi/retry_spec.lua
- spec/yazi/ya_process_spec.lua
> refactor: consolidate retry logic to its own module

- integration-tests/cypress/e2e/yazi-keymappings.cy.ts
- lua/yazi/keybinding_helpers.lua
Previously, if only one buffer was open, the command would do nothing. Now, it will cycle to the first buffer.
Closes https://github.com/mikavilpas/yazi.nvim/issues/914
> fix: cycling buffers with `<tab>` works with only one buffer open

- lua/yazi/event_handling/yazi_event_handling.lua
Issue
=====
The error below was logged when running the unit tests with `just test`:
```rs
117 successes / 0 failures / 0 errors / 0 pending : 0.360738 seconds
Error executing callback:
.../site/pack/vendor/start/plenary.nvim/lua/plenary/log.lua:12: E5560: Vimscript function must not be called in a fast event context
stack traceback:
[C]: in function 'getenv'
.../site/pack/vendor/start/plenary.nvim/lua/plenary/log.lua:12: in main chunk
[C]: in function 'require'
...embedded-lsp-file-operations/lsp-file-operations/log.lua:1: in main chunk
[C]: in function 'require'
...bedded-lsp-file-operations/lsp-file-operations/utils.lua:4: in main chunk
[C]: in function 'require'
...-lsp-file-operations/lsp-file-operations/will-delete.lua:2: in main chunk
[C]: in function 'require' …
```
> test: lazy load lsp-file-operations to avoid fast event error

- .github/workflows/test.yml
This was kindly fixed in https://github.com/sxyazi/yazi/pull/2719
> ci: bump yazi to include fix for missing `hover` event after `cd`

- README.md
- documentation/copy-relative-path-to-files.md
- integration-tests/cypress/e2e/integrations.cy.ts
- integration-tests/cypress/e2e/lsp.cy.ts
- integration-tests/test-environment/.config/nvim/init.lua
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/integrations/snacks_relative_path.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- spec/yazi/relative_path_spec.lua
yazi.nvim has had the ability to copy the relative path to files for a
while now (default `<c-y>`). This commit adds the ability to do the same in
the snacks.nvim picker. It's not enabled by default.
When the snacks.nvim picker is open, you can press your keybinding for
this, and it will copy the relative paths to the selected file(s) to the
clipboard register.
To learn how to use this, you can read the documentation in the readme
file.
Not the entire yazi config.
> feat(snacks): add copy relative path action to snacks.nvim picker

- README.md
- documentation/emitting-commands-to-yazi.md
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/yazi-keymappings.cy.ts
- integration-tests/test-environment/config-modifications/add_keybinding_to_start_yazi_and_find.lua
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/process/yazi_process_api.lua
- lua/yazi/types.lua
When Yazi is running, it supports receiving instructions to execute yazi commands. These can be sent using `ya emit-to`:
- https://yazi-rs.github.io/docs/dds#ya-emit
Provide two things to take advantage of this:
- a new `on_yazi_ready` hook that is called when yazi is ready to receive commands
- a new `emit_to_yazi` method on the YaziProcessApi that allows sending commands to yazi.
This allows starting yazi in various interesting states, such as immediately entering find mode.
More detailed documentation can be found in the features section of the readme.
Closes https://github.com/mikavilpas/yazi.nvim/issues/944
> feat: allow emitting arbitrary yazi commands after yazi is ready

- integration-tests/package.json
- lua/yazi/config.lua
- package.json
- pnpm-lock.yaml
- spec/yazi/yazi_config_spec.lua
yazi.nvim supports the `winborder` option added in Neovim 0.11. Back when this feature was added, it was not available in stable Neovim, so I added protections to prevent errors when the option was not available.
Now that Neovim 0.11 is the minimum supported version, we can remove these fallbacks and simplify the code.
> refactor: remove fallbacks for missing winborder option

- README.md
The old Gitee repo is no longer reachable. Looks like the author (probably) has moved to GitHub. Recommend using the new repo.
> docs: switch easyjump repo to GitHub

- lua/yazi/process/yazi_process.lua
- lua/yazi/types.lua
in case you'd like a separate config from the main cli yazi config
usage in init.lua:
```
{
"mikavilpas/yazi.nvim",
event = "VeryLazy",
dependencies = {
-- check the installation instructions at
-- https://github.com/folke/snacks.nvim
"folke/snacks.nvim"
},
opts = {
config_home = "~/.config/nvim/yazi/"
},
},
```
> feat: add option for nvim yazi to use a custom config file 

- lua/yazi/keybinding_helpers.lua
```rs
  Error  14:24:28 msg_show.lua_error vim.schedule callback: ...mikavilpas/git/yazi.nvim/lua/yazi/keybinding_helpers.lua:72: attempt to index local 'visible_buffer' (a nil value)
stack traceback:
...mikavilpas/git/yazi.nvim/lua/yazi/keybinding_helpers.lua:72: in function 'show_visible_buffer'
...mikavilpas/git/yazi.nvim/lua/yazi/keybinding_helpers.lua:153: in function 'cycle_open_buffers'
...azi.nvim/lua/yazi/event_handling/yazi_event_handling.lua:123: in function 'process_events_emitted_from_yazi'
...mikavilpas/git/yazi.nvim/lua/yazi/process/ya_process.lua:244: in function <...mikavilpas/git/yazi.nvim/lua/yazi/process/ya_process.lua:242>
```
> fix: crash when pressing tab if visible-buffer is nil

- .github/workflows/test.yml
- integration-tests/package.json
- package.json
- pnpm-lock.yaml
https://github.com/sxyazi/yazi/releases/tag/v25.5.28
> ci: bump yazi to newest stable, from ea90b0477ecc to v25.5.28

- lua/yazi/window.lua
Floating windows were misaligned vertically when `cmdheight` was set to 0, as is common when using plugins like `noice.nvim`. This change adjusts the row offset calculation by subtracting a line from the total height, ensuring proper centering even when the command line is hidden.
> fix(ui): correctly center floating window when cmdheight=0

- .github/workflows/test.yml
https://github.com/mikavilpas/yazi.nvim/actions/runs/15942244922/job/44971856978?pr=1011
```sh
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/universe/f/fzf/fzf_0.44.1-1ubuntu0.2_amd64.deb  404  Not Found [IP: 52.252.163.49 80]
146
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
> ci: try to fix fzf not found error

- README.md
- integration-tests/package.json
- integration-tests/test-environment/.config/nvim/init.lua
- lua/yazi/process/ya_process.lua
- package.json
- pnpm-lock.yaml
This should have no effect on anything, just a type/documentation level
change.
> refactor: `yazi_id` and `yazi_process_id` are actually mandatory

- README.md
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/reading-events.cy.ts
- integration-tests/test-environment/config-modifications/add_command_to_show_loaded_packages.lua
- lazy.lua
- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/health.lua
- lua/yazi/integrations/snacks_bufdelete.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
- pnpm-lock.yaml
- spec/yazi/trash_spec.lua
**Issue:**
For a long time, snacks.nvim had been a dependency of yazi.nvim. Originally I had big plans for using it extensively, but they have not materialized (yet).
Snacks is still a dependency by default, although only a very small part of it is used: the `snacks.bufdelete` module, which is used to delete buffers while preserving the window layout.
Previously, `future_features.process_events_live` has been set to `true` by default, but because the built-in way of closing buffers was found to disturb the window layout, it was recommended to use `snacks.bufdelete` instead.
**Solution:**
Bundle a copy of `snacks.bufdelete` in yazi.nvim, so that snacks.nvim is not required anymore.
Turn this on by default, but allow users to disable it by setting …
> refactor: make snacks.nvim optional by bundling snacks.bufdelete

- integration-tests/cypress/e2e/cd-to-buffer-with-ya-emit.cy.ts
- integration-tests/cypress/e2e/lsp.cy.ts
- integration-tests/cypress/e2e/opening-files.cy.ts
- integration-tests/cypress/e2e/toggling.cy.ts
- integration-tests/cypress/e2e/utils/yazi-utils.ts
**Issue:**
Previously, the tests were waiting for a specific text in yazi's footer to be visible to determine if yazi was ready. The terminal can sometimes shift out of view in CI, so this is not a reliable way.
**Solution:**
Use the internal way of polling for yazi to be ready (`assertYaziIsReady`), which was added some time ago but is not used in all of the tests yet.
> test: use internal way of polling for yazi to be ready

- integration-tests/test-environment/.config/nvim/init.lua
**Issue:**
Previously, the `vim.lsp.enable("lua-language-server")` call was made in the test environment's `init.lua` file, but it was using the wrong server name.
The tests still worked because the `mason-lspconfig` plugin was automatically enabling the `lua_ls` as it's installed on my system. However, this is magic behaviour that is hard to maintain and understand.
**Solution:**
Make using the desired LSP server explicit by disabling `automatic_enable` of the LSP server, and then explicitly calling `vim.lsp.enable("lua_ls")`.
> test: correctly call `vim.lsp.enable` to enable LSP in tests

- lua/yazi/types.lua
- lua/yazi/utils.lua
- spec/yazi/delete_spec.lua
- spec/yazi/read_events_spec.lua
- spec/yazi/rename_spec.lua
- spec/yazi/trash_spec.lua
- spec/yazi/ya_process_spec.lua
Previously, the `id` field was sometimes called `yazi_id` and sometimes just `id`. This just modifies what the field is called, but has no effect on the functionality.
> refactor: use `yazi_id` instead of `id` in Yazi DDS events

- .github/workflows/test.yml
- integration-tests/cypress/e2e/integrations.cy.ts
- integration-tests/package.json
- package.json
- pnpm-lock.yaml
- spec/yazi/ya_process_spec.lua
Now using
https://github.com/sxyazi/yazi/commit/6366e46c23da43f7aae7f083d00fd989321b9638
refactor: use term "core" instead of "context" (#2978)
> ci: bump nightly yazi from 2025-06-29 to 2025-07-11

- documentation/plugin-management.md
- lua/yazi/plugin.lua
- spec/yazi/plugin_spec.lua
**Issue:**
Using the built-in lazy.nvim-based plugin management system, it's only possible to install plugins from a subdirectory of the plugin's root directory. This works fine for e.g. https://github.com/yazi-rs/plugins/ which provides all the plugins as exactly one level deep from the repo root.
However, some plugins may be located in a deeply nested subdirectory such as `deeply/nested/plugin.yazi`, and the current implementation puts them in `~/.config/yazi/plugins/deeply/nested/plugin.yazi` which does not work with yazi.
Docs for this feature:
- https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/plugin-management.md
**Solution:**
Allow passing in a `name` option to the `build_plugin` and `build_flavor` functions, which will be used as the name of the symlinked plugin or …
> feat: support installing plugins from deeply nested subdirectories

- integration-tests/package.json
- lua/yazi/process/ya_process.lua
- pnpm-lock.yaml
- spec/yazi/ya_process_spec.lua
Might help
https://github.com/mikavilpas/yazi.nvim/issues/1049#issuecomment-3137184040
> fix: only handle `cd` events for the current yazi instance

- lua/yazi/hijack_netrw.lua
Not sure if this is an actual issue, but it seems like the hijack_netrw function can be called multiple times if yazi.setup() is called more than once. It could set up multiple event handlers and cause unexpected behavior.
Better to disallow it for now.
> fix: only hijack netrw once on multiple yazi.setup() calls

- lua/yazi.lua
- lua/yazi/config.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/types.lua
- package.json
- spec/yazi/ya_process_spec.lua
I had previously implemented tracking the cwd using ya and listening to
the `cd` and `hover` events. It's more reliable to use `--cwd-file`
since ya seems to have some trouble starting on some systems right now.
`cwd-file` is entioned here:
https://yazi-rs.github.io/docs/configuration/keymap/#mgr.quit
> fix: resolve the last directory using the `--cwd-file` option

- README.md
- integration-tests/MyTestDirectory.ts
- integration-tests/cypress/e2e/opening-files.cy.ts
- integration-tests/cypress/e2e/utils/neovim-utils.ts
- integration-tests/test-environment/config-modifications/yazi_config/enable_change_neovim_cwd_on_close.lua
- lua/yazi/config.lua
- lua/yazi/process/yazi_process.lua
- lua/yazi/types.lua
- lua/yazi/utils.lua
When yazi is closed with no files selected, it can now change Neovim's
current working directory to the directory that yazi was in before it
was closed. It's off by default.
To use this, set `change_neovim_cwd_on_close = true` in your yazi.nvim
configuration.
Closes https://github.com/mikavilpas/yazi.nvim/issues/617
> feat(opt-in): change Neovim's cwd when no files are selected in yazi

- README.md
- lua/yazi/config.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/types.lua
- spec/yazi/ya_process_spec.lua
feat: allow customizing the way file paths are escaped
**Issue:**
Depending on the user's operating system, shell, and neovim settings,
the way file paths are escaped before being passed to yazi commands may
need to be customized.
**Solution:**
Allow customizing this with
`config.integrations.escape_path_implementation`, which has the type
`escape_path_implementation? fun(path: string): string`.
Examples of possible implementations:
```lua
-- example: replace / with \
config.integrations.escape_path_implementation = function(path)
-- string.gsub() returns multiple values, so we take the first one to
-- keep the Lua LSP happy
local result = path:gsub("/", "\\")
return result
end
```
The default implementation uses `vim.fn.shellescape` (as it did before
this change), which is usually …
> feat: allow customizing the way file paths are escaped

- lua/yazi/process/ya_process.lua
- lua/yazi/types.lua
- spec/yazi/ya_process_spec.lua
This tries to avoid issues related to different shell escaping implementations on different platforms. It might be possible to avoid using shell escaping altogether by passing the paths as a table to `vim.fn.jobstart()`, which handles the escaping internally.
This is now on by default, but can be disabled by setting `future_features.new_shell_escaping = false` in the configuration. Please open an issue if you encounter any problems with this.
Related issue: https://github.com/mikavilpas/yazi.nvim/issues/1101
> fix: avoid using shell escaping for passing paths to yazi

- lua/yazi/config.lua
- spec/yazi/ya_process_spec.lua
It was supposed to be on in the previous commit, but was accidentally left off.
> fix: enable new shell escaping feature

- .github/workflows/test.yml
- README.md
Dependabot is used to automatically create pull requests for testing related dependencies. These do not affect the neovim functionality of this plugin in any way, and users should not be concerned about these updates.
This is an internal change done to reduce the maintenance burden of this repository.
It will create more frequent commits to the repository, so users are recommended to set the version manager to only update to the newest releases, and not to the latest commit. I added an example of this to the readme file.
- https://lazy.folke.io/spec/versioning
- https://github.com/echasnovski/mini.deps
> ci: automerge dependabot updates when tests pass

- .github/workflows/test.yml
- integration-tests/MyTestDirectory.ts
- integration-tests/test-environment/.config/nvim_integrations/prepare.lua
- integration-tests/tsconfig.json
- integration-tests/tui-sandbox.config.ts
- package.json
> Updates for tests etc

- .github/workflows/lint.yml
https://github.com/mikavilpas/yazi.nvim/pull/1208#pullrequestreview-3237227226
---
Check warning Code scanning / CodeQL
Workflow does not contain permissions Medium
Actions job or workflow does not limit the permissions of the GITHUB_TOKEN. Consider setting an explicit permissions block, using the following as a minimal starting point: {contents: read} Show more details Dismiss alert Copilot Autofix AI 4 minutes ago
To fix this issue, add a top-level permissions block to limit the default permissions granted to the GITHUB_TOKEN for all jobs in the workflow. In this case, the minimal required permission is typically contents: read unless a job requires more. Based on the shown actions (checkout, linters), contents: read should be sufficient. The fix is to add:
```yaml
permissions: …
```
> refactor(ci): constrain permissions for GITHUB_TOKEN in linting

- README.md
- lua/yazi/config.lua
- lua/yazi/process/ya_process.lua
- lua/yazi/types.lua
- spec/yazi/ya_process_spec.lua
BREAKING CHANGE: removed `integrations.escape_path_implementation` (function) and `future_features.new_shell_escaping` (boolean).
The custom shell escaping implementation is no longer needed, as we found a better way to handle starting yazi in
https://github.com/mikavilpas/yazi.nvim/issues/1101 that should avoid all kinds of shell related issues on all platforms.
It has been automatically enabled by default for almost two months without any issues.
Nobody seems to be using this feature, and we haven't had any bug reports about it since it was merged in
https://github.com/mikavilpas/yazi.nvim/pull/1102
I left the old implementation in as a precaution for users to optionally toggle it back on, but I think it's safe to remove it completely.
> refactor!: disable custom shell escaping as unneeded

- .github/workflows/test.yml
- documentation/yazi-keymappings.md
- integration-tests/cypress/e2e/reading-events.cy.ts
- integration-tests/cypress/e2e/yazi-keymappings.cy.ts
- integration-tests/test-environment/.config/yazi/keymap.toml
- integration-tests/test-environment/config-modifications/notify_custom_events.lua
- lua/yazi/config.lua
- lua/yazi/utils.lua
**Issue:**
The following issue has started happening on nightly Yazi 25.9.15
(30c02795 2025-09-20):
```sh
$ ya pub-to 0 NvimCycleBuffer
Cannot send message: Kind `NvimCycleBuffer` must be in kebab-case
```
This breaks the e2e tests because they are sending custom `ya` events in
PascalCase. Stable yazi is not affected.
**Solution:**
It looks like nobody but myself is using this feature, so make a
breaking change and require switching to use kebab-case.
Users using the `NvimCycleBuffer` event in their yazi `keymap.toml` need
to change their yazi config accordingly:
In `/Users/mikavilpas/dotfiles/.config/yazi/keymap.toml`:
```diff
[[mgr.prepend_keymap]]
on = "<tab>"
-run = """shell "ya pub-to 0 NvimCycleBuffer""""
+run = """shell "ya pub-to 0 nvim-cycle-buffer""""
```
---
chore(deps): update …
> refactor!: custom events need to use kebab-case

- .github/workflows/test.yml
- renovate.json
This drops the need to maintain our own copy of the regex. Many usage examples are available with the github search.
https://docs.renovatebot.com/presets-customManagers/#custommanagersgithubactionsversions
> refactor(renovate): use the built-in githubActionsVersions manager
